#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
H3C交换机命令手册 - 完整版
"""

H3C_COMMANDS = {
    "基础配置": {
        "系统管理": {
            "进入系统视图": {"command": "system-view", "description": "从用户视图进入系统视图", "example": "<H3C> system-view\n[H3C]"},
            "修改设备名称": {"command": "sysname <name>", "description": "设置交换机主机名", "example": "[H3C] sysname SW-Core\n[SW-Core]"},
            "显示当前配置": {"command": "display current-configuration", "description": "查看当前运行配置", "example": "[H3C] display current-configuration"},
            "显示保存配置": {"command": "display saved-configuration", "description": "查看已保存的配置", "example": "[H3C] display saved-configuration"},
            "保存配置": {"command": "save", "description": "保存当前配置到存储器", "example": "[H3C] save"},
            "重启设备": {"command": "reboot", "description": "重启交换机", "example": "<H3C> reboot"},
            "恢复出厂配置": {"command": "reset saved-configuration\nreboot", "description": "清除配置并重启恢复出厂", "example": "<H3C> reset saved-configuration\n<H3C> reboot"},
            "查看系统信息": {"command": "display version", "description": "查看设备版本和硬件信息", "example": "<H3C> display version"},
            "配置系统时间": {"command": "clock datetime <HH:MM:SS> <YYYY-MM-DD>", "description": "设置系统时间", "example": "<H3C> clock datetime 14:30:00 2024-01-15"},
            "查看系统资源": {"command": "display cpu\ndisplay memory", "description": "查看CPU和内存使用率", "example": "<H3C> display cpu"},
            "配置闲置超时": {"command": "idle-timeout <minutes> [seconds]", "description": "设置用户界面闲置超时时间", "example": "[H3C] user-interface console 0\n[H3C-ui-console0] idle-timeout 30 0"},
            "查看启动文件": {"command": "display boot-loader", "description": "查看下次启动文件", "example": "<H3C> display boot-loader"},
            "设置启动文件": {"command": "boot-loader file <file-path>", "description": "设置下次启动文件", "example": "<H3C> boot-loader file flash:/s5500.bin"}
        },
        "用户与权限管理": {
            "创建本地用户": {"command": "local-user <username>", "description": "创建本地用户账号", "example": "[H3C] local-user admin"},
            "设置用户密码": {"command": "password <cipher|simple> <password>", "description": "设置用户密码(cipher密文/simple明文)", "example": "[H3C-luser-admin] password simple Admin@123"},
            "设置用户权限级别": {"command": "authorization-attribute level <0-3>", "description": "设置用户权限级别(0访客,1监控,2系统,3管理)", "example": "[H3C-luser-admin] authorization-attribute level 3"},
            "设置用户服务类型": {"command": "service-type <ssh|telnet|terminal|ftp|http>", "description": "设置用户允许的服务类型", "example": "[H3C-luser-admin] service-type ssh telnet"},
            "设置Super密码": {"command": "super password <cipher|simple> <password>", "description": "设置切换用户级别密码", "example": "[H3C] super password simple Super@123"},
            "用户界面配置": {"command": "user-interface <console|vty> <first> [last]", "description": "进入用户界面配置", "example": "[H3C] user-interface vty 0 4"},
            "设置登录认证方式": {"command": "authentication-mode <none|password|scheme>", "description": "设置用户界面认证模式", "example": "[H3C-ui-vty0-4] authentication-mode scheme"},
            "查看在线用户": {"command": "display users", "description": "查看当前登录用户", "example": "<H3C> display users"},
            "强制踢出用户": {"command": "free user-interface <type> <number>", "description": "强制断开指定用户连接", "example": "<H3C> free user-interface vty 1"},
            "设置用户属性": {"command": "local-user <user> <attribute>", "description": "设置用户各种属性", "example": "[H3C] local-user admin state active"}
        },
        "SSH配置": {
            "生成RSA密钥": {"command": "public-key local create rsa [bits]", "description": "生成本地RSA密钥对", "example": "[H3C] public-key local create rsa 2048"},
            "生成DSA密钥": {"command": "public-key local create dsa", "description": "生成本地DSA密钥对", "example": "[H3C] public-key local create dsa"},
            "生成ECDSA密钥": {"command": "public-key local create ecdsa", "description": "生成本地ECDSA密钥对", "example": "[H3C] public-key local create ecdsa"},
            "启用SSH服务": {"command": "ssh server enable", "description": "启用SSH服务器", "example": "[H3C] ssh server enable"},
            "设置SSH版本": {"command": "ssh server compatible-ssh1x enable", "description": "兼容SSHv1(默认只用v2)", "example": "[H3C] ssh server compatible-ssh1x enable"},
            "创建SSH用户": {"command": "ssh user <username> service-type stelnet authentication-type <password|publickey|all>", "description": "创建SSH用户", "example": "[H3C] ssh user admin service-type stelnet authentication-type password"},
            "配置VTY允许SSH": {"command": "user-interface vty 0 4\nprotocol inbound ssh", "description": "VTY只允许SSH连接", "example": "[H3C] user-interface vty 0 4\n[H3C-ui-vty0-4] protocol inbound ssh"},
            "SSH超时配置": {"command": "ssh server timeout <seconds>", "description": "设置SSH连接超时", "example": "[H3C] ssh server timeout 60"},
            "SSH重试次数": {"command": "ssh server authentication-retries <times>", "description": "设置SSH认证重试次数", "example": "[H3C] ssh server authentication-retries 3"},
            "查看SSH状态": {"command": "display ssh server status\ndisplay ssh user-information", "description": "查看SSH服务状态", "example": "<H3C> display ssh server status"},
            "查看SSH会话": {"command": "display ssh server session", "description": "查看SSH会话", "example": "<H3C> display ssh server session"},
            "导入公钥": {"command": "public-key peer <name> import sshkey <key-string>", "description": "导入SSH公钥", "example": "[H3C] public-key peer user1 import sshkey ssh-rsa AAAA..."},
            "首次登录设置": {"command": "ssh client first-time enable", "description": "客户端首次登录免确认", "example": "[H3C] ssh client first-time enable"}
        },
        "Telnet配置": {
            "启用Telnet服务": {"command": "telnet server enable", "description": "启用Telnet服务器(不安全)", "example": "[H3C] telnet server enable"},
            "配置VTY允许Telnet": {"command": "user-interface vty 0 4\nprotocol inbound telnet", "description": "VTY允许Telnet连接", "example": "[H3C] user-interface vty 0 4\n[H3C-ui-vty0-4] protocol inbound telnet"},
            "设置Telnet端口": {"command": "telnet server port <port>", "description": "修改Telnet服务端口", "example": "[H3C] telnet server port 2323"},
            "关闭Telnet服务": {"command": "undo telnet server enable", "description": "关闭Telnet服务提高安全性", "example": "[H3C] undo telnet server enable"}
        },
        "Console配置": {
            "配置Console密码": {"command": "user-interface console 0\nauthentication-mode password\nset authentication password <cipher|simple> <password>", "description": "设置Console登录密码", "example": "[H3C] user-interface console 0\n[H3C-ui-console0] authentication-mode password\n[H3C-ui-console0] set authentication password simple Console@123"},
            "Console认证模式": {"command": "authentication-mode <none|password|scheme>", "description": "设置Console认证模式", "example": "[H3C-ui-console0] authentication-mode scheme"},
            "Console波特率": {"command": "speed <baud-rate>", "description": "设置Console波特率", "example": "[H3C-ui-console0] speed 115200"}
        },
        "域名解析": {
            "配置DNS服务器": {"command": "dns server <ip>", "description": "配置DNS服务器地址", "example": "[H3C] dns server 8.8.8.8\n[H3C] dns server 114.114.114.114"},
            "配置域名后缀": {"command": "dns domain <domain-name>", "description": "配置默认域名后缀", "example": "[H3C] dns domain example.com"},
            "启用DNS解析": {"command": "dns resolve", "description": "启用DNS域名解析功能", "example": "[H3C] dns resolve"},
            "静态DNS映射": {"command": "ip host <hostname> <ip>", "description": "配置静态主机名解析", "example": "[H3C] ip host server1 192.168.1.100"},
            "测试DNS解析": {"command": "ping <hostname>", "description": "测试域名解析", "example": "<H3C> ping www.google.com"}
        }
    },
    "接口配置": {
        "以太网接口": {
            "进入接口视图": {"command": "interface <interface-type> <interface-number>", "description": "进入指定接口配置视图", "example": "[H3C] interface GigabitEthernet 1/0/1\n[H3C-GigabitEthernet1/0/1]"},
            "接口描述": {"command": "description <text>", "description": "为接口添加描述信息", "example": "[H3C-GigabitEthernet1/0/1] description To_Server_Room"},
            "开启接口": {"command": "undo shutdown", "description": "开启接口", "example": "[H3C-GigabitEthernet1/0/1] undo shutdown"},
            "关闭接口": {"command": "shutdown", "description": "关闭接口", "example": "[H3C-GigabitEthernet1/0/1] shutdown"},
            "配置接口IP": {"command": "ip address <ip> <mask> [sub]", "description": "配置接口IP地址", "example": "[H3C-GigabitEthernet1/0/1] ip address 192.168.1.1 255.255.255.0"},
            "配置从IP": {"command": "ip address <ip> <mask> sub", "description": "配置接口从IP地址", "example": "[H3C-GigabitEthernet1/0/1] ip address 192.168.2.1 255.255.255.0 sub"},
            "删除接口IP": {"command": "undo ip address", "description": "删除接口IP地址", "example": "[H3C-GigabitEthernet1/0/1] undo ip address"},
            "设置接口速率": {"command": "speed <10|100|1000|auto>", "description": "设置接口速率", "example": "[H3C-GigabitEthernet1/0/1] speed 1000"},
            "设置双工模式": {"command": "duplex <half|full|auto>", "description": "设置接口双工模式", "example": "[H3C-GigabitEthernet1/0/1] duplex full"},
            "接口流量统计": {"command": "flow-interval <interval>", "description": "设置接口流量统计间隔", "example": "[H3C-GigabitEthernet1/0/1] flow-interval 60"},
            "查看接口状态": {"command": "display interface <interface>", "description": "查看接口详细状态", "example": "<H3C> display interface GigabitEthernet 1/0/1"},
            "查看接口简要": {"command": "display interface brief", "description": "查看所有接口简要状态", "example": "<H3C> display interface brief"},
            "接口环回检测": {"command": "loopback-detection enable", "description": "启用接口环回检测", "example": "[H3C-GigabitEthernet1/0/1] loopback-detection enable"}
        },
        "VLAN接口": {
            "创建VLAN": {"command": "vlan <vlan-id>", "description": "创建VLAN", "example": "[H3C] vlan 10"},
            "批量创建VLAN": {"command": "vlan <vlan-id-list>", "description": "批量创建多个VLAN", "example": "[H3C] vlan 10 20 30\n或 [H3C] vlan 10 to 20"},
            "VLAN命名": {"command": "name <vlan-name>", "description": "为VLAN设置名称", "example": "[H3C-vlan10] name Sales_Department"},
            "删除VLAN": {"command": "undo vlan <vlan-id>", "description": "删除指定VLAN", "example": "[H3C] undo vlan 10"},
            "查看VLAN": {"command": "display vlan", "description": "查看所有VLAN信息", "example": "<H3C> display vlan"},
            "查看指定VLAN": {"command": "display vlan <vlan-id>", "description": "查看指定VLAN详细信息", "example": "<H3C> display vlan 10"},
            "创建VLAN接口": {"command": "interface Vlan-interface <vlan-id>", "description": "创建VLAN三层接口", "example": "[H3C] interface Vlan-interface 10"},
            "VLAN接口配置IP": {"command": "interface Vlan-interface <vlan-id>\nip address <ip> <mask>", "description": "为VLAN接口配置IP地址", "example": "[H3C] interface Vlan-interface 10\n[H3C-Vlan-interface10] ip address 192.168.10.1 255.255.255.0"},
            "VLAN接口描述": {"command": "description <text>", "description": "为VLAN接口添加描述", "example": "[H3C-Vlan-interface10] description Gateway_for_VLAN10"}
        },
        "接口VLAN": {
            "Access接口": {"command": "port link-type access\nport access vlan <vlan-id>", "description": "配置接口为Access模式并加入VLAN", "example": "[H3C-GigabitEthernet1/0/1] port link-type access\n[H3C-GigabitEthernet1/0/1] port access vlan 10"},
            "Trunk接口": {"command": "port link-type trunk\nport trunk permit vlan <vlan-id-list>", "description": "配置接口为Trunk模式", "example": "[H3C-GigabitEthernet1/0/24] port link-type trunk\n[H3C-GigabitEthernet1/0/24] port trunk permit vlan 10 20 30"},
            "Trunk允许所有VLAN": {"command": "port trunk permit vlan all", "description": "Trunk允许所有VLAN通过", "example": "[H3C-GigabitEthernet1/0/24] port trunk permit vlan all"},
            "Trunk PVID": {"command": "port trunk pvid vlan <vlan-id>", "description": "设置Trunk接口PVID", "example": "[H3C-GigabitEthernet1/0/24] port trunk pvid vlan 99"},
            "Hybrid接口": {"command": "port link-type hybrid", "description": "配置接口为Hybrid模式", "example": "[H3C-GigabitEthernet1/0/1] port link-type hybrid"},
            "Hybrid Untagged": {"command": "port hybrid vlan <vlan-id-list> untagged", "description": "Hybrid接口剥离VLAN标签", "example": "[H3C-GigabitEthernet1/0/1] port hybrid vlan 10 20 untagged"},
            "Hybrid Tagged": {"command": "port hybrid vlan <vlan-id-list> tagged", "description": "Hybrid接口保留VLAN标签", "example": "[H3C-GigabitEthernet1/0/1] port hybrid vlan 100 tagged"},
            "Hybrid PVID": {"command": "port hybrid pvid vlan <vlan-id>", "description": "设置Hybrid接口PVID", "example": "[H3C-GigabitEthernet1/0/1] port hybrid pvid vlan 10"},
            "QinQ配置": {"command": "qinq enable", "description": "启用QinQ功能", "example": "[H3C-GigabitEthernet1/0/1] qinq enable"}
        },
        "链路聚合": {
            "创建聚合接口": {"command": "interface Bridge-Aggregation <trunk-id>", "description": "创建链路聚合接口", "example": "[H3C] interface Bridge-Aggregation 1"},
            "配置聚合模式": {"command": "link-aggregation mode <dynamic|static>", "description": "设置链路聚合模式", "example": "[H3C-Bridge-Aggregation1] link-aggregation mode dynamic"},
            "成员接口加入": {"command": "port link-aggregation group <trunk-id>", "description": "将物理接口加入聚合组", "example": "[H3C-GigabitEthernet1/0/1] port link-aggregation group 1"},
            "设置最大活跃链路": {"command": "link-aggregation selected-port maximum <number>", "description": "设置最大活跃链路数", "example": "[H3C-Bridge-Aggregation1] link-aggregation selected-port maximum 4"},
            "设置最小活跃链路": {"command": "link-aggregation selected-port minimum <number>", "description": "设置最小活跃链路数", "example": "[H3C-Bridge-Aggregation1] link-aggregation selected-port minimum 2"},
            "配置负载均衡": {"command": "link-aggregation load-sharing mode <source-mac|destination-mac|source-ip|destination-ip>", "description": "设置负载均衡算法", "example": "[H3C] link-aggregation load-sharing mode source-ip destination-ip"},
            "查看聚合状态": {"command": "display link-aggregation summary", "description": "查看链路聚合状态", "example": "<H3C> display link-aggregation summary"},
            "查看详细聚合": {"command": "display link-aggregation verbose [Bridge-Aggregation <id>]", "description": "查看聚合详细状态", "example": "<H3C> display link-aggregation verbose Bridge-Aggregation 1"},
            "LACP优先级": {"command": "lacp system-priority <priority>", "description": "设置LACP系统优先级", "example": "[H3C] lacp system-priority 100"},
            "接口LACP优先级": {"command": "lacp port-priority <priority>", "description": "设置接口LACP优先级", "example": "[H3C-GigabitEthernet1/0/1] lacp port-priority 100"}
        }
    },
    "路由配置": {
        "静态路由": {
            "配置静态路由": {"command": "ip route-static <dest-network> <mask> <next-hop> [preference <preference>]", "description": "配置静态路由", "example": "[H3C] ip route-static 192.168.100.0 255.255.255.0 10.0.0.1"},
            "默认路由": {"command": "ip route-static 0.0.0.0 0 <gateway>", "description": "配置默认路由", "example": "[H3C] ip route-static 0.0.0.0 0 192.168.1.254"},
            "配置路由优先级": {"command": "ip route-static <dest> <mask> <next-hop> preference <preference>", "description": "设置静态路由优先级", "example": "[H3C] ip route-static 10.0.0.0 24 192.168.1.1 preference 10"},
            "路由标记": {"command": "ip route-static <dest> <mask> <next-hop> tag <tag>", "description": "为路由设置标记", "example": "[H3C] ip route-static 192.168.0.0 16 10.0.0.1 tag 100"},
            "黑洞路由": {"command": "ip route-static <dest> <mask> NULL0", "description": "配置黑洞路由丢弃流量", "example": "[H3C] ip route-static 10.10.0.0 24 NULL0"},
            "删除静态路由": {"command": "undo ip route-static <dest> <mask> <next-hop>", "description": "删除指定静态路由", "example": "[H3C] undo ip route-static 192.168.100.0 255.255.255.0 10.0.0.1"},
            "查看路由表": {"command": "display ip routing-table", "description": "查看IP路由表", "example": "<H3C> display ip routing-table"},
            "查看静态路由": {"command": "display ip routing-table protocol static", "description": "只查看静态路由", "example": "<H3C> display ip routing-table protocol static"},
            "路由追踪": {"command": "tracert <ip>", "description": "追踪到目标的路径", "example": "<H3C> tracert 8.8.8.8"}
        },
        "OSPF配置": {
            "启用OSPF进程": {"command": "ospf <process-id> [router-id <router-id>]", "description": "启动OSPF进程", "example": "[H3C] ospf 1 router-id 1.1.1.1"},
            "进入区域配置": {"command": "area <area-id>", "description": "进入OSPF区域配置", "example": "[H3C-ospf-1] area 0"},
            "宣告网络": {"command": "network <network> <wildcard>", "description": "宣告直连网络到OSPF", "example": "[H3C-ospf-1-area-0.0.0.0] network 192.168.0.0 0.0.255.255"},
            "配置区域类型": {"command": "area <area-id>\n[nssa|stub] [no-summary]", "description": "配置NSSA或Stub区域", "example": "[H3C-ospf-1-area-0.0.0.1] nssa no-summary"},
            "设置OSPF优先级": {"command": "preference <preference>", "description": "设置OSPF路由优先级", "example": "[H3C-ospf-1] preference 10"},
            "配置被动接口": {"command": "silent-interface <interface>", "description": "禁止接口发送OSPF报文", "example": "[H3C-ospf-1] silent-interface Vlan-interface10"},
            "配置OSPF认证": {"command": "area <area-id>\nauthentication-mode <simple|md5> <password>", "description": "配置区域认证", "example": "[H3C-ospf-1-area-0.0.0.0] authentication-mode md5 plain H3C@123"},
            "配置接口认证": {"command": "interface <interface>\nospf authentication-mode <md5|simple> <password>", "description": "配置接口级OSPF认证", "example": "[H3C-GigabitEthernet1/0/1] ospf authentication-mode md5 1 plain H3C@123"},
            "设置DR优先级": {"command": "interface <interface>\nospf dr-priority <priority>", "description": "设置接口DR选举优先级", "example": "[H3C-GigabitEthernet1/0/1] ospf dr-priority 100"},
            "设置接口开销": {"command": "interface <interface>\nospf cost <cost>", "description": "设置OSPF接口开销", "example": "[H3C-GigabitEthernet1/0/1] ospf cost 10"},
            "查看OSPF邻居": {"command": "display ospf peer", "description": "查看OSPF邻居关系", "example": "<H3C> display ospf peer"},
            "查看OSPF路由": {"command": "display ospf routing", "description": "查看OSPF路由", "example": "<H3C> display ospf routing"},
            "查看OSPF接口": {"command": "display ospf interface", "description": "查看OSPF接口信息", "example": "<H3C> display ospf interface"},
            "重置OSPF进程": {"command": "reset ospf process", "description": "重启OSPF进程", "example": "<H3C> reset ospf process"}
        },
        "BGP配置": {
            "启动BGP进程": {"command": "bgp <as-number>\nrouter-id <router-id>", "description": "启动BGP进程并设置Router-ID", "example": "[H3C] bgp 65001\n[H3C-bgp] router-id 1.1.1.1"},
            "配置BGP邻居": {"command": "peer <ip> as-number <as-number>", "description": "配置BGP对等体", "example": "[H3C-bgp] peer 10.0.0.2 as-number 65002"},
            "配置IBGP邻居": {"command": "peer <ip> as-number <local-as>", "description": "配置IBGP对等体(同AS)", "example": "[H3C-bgp] peer 192.168.1.2 as-number 65001"},
            "指定更新源": {"command": "peer <ip> connect-interface <interface>", "description": "指定BGP更新源接口", "example": "[H3C-bgp] peer 10.0.0.2 connect-interface LoopBack0"},
            "宣告BGP网络": {"command": "address-family ipv4\nnetwork <network> mask <mask>", "description": "宣告网络到BGP", "example": "[H3C-bgp] address-family ipv4\n[H3C-bgp-ipv4] network 192.168.0.0 255.255.0.0"},
            "配置下一跳本地": {"command": "peer <ip> next-hop-local", "description": "设置向IBGP邻居发布路由时下一跳为本地", "example": "[H3C-bgp-ipv4] peer 192.168.1.2 next-hop-local"},
            "引入直连路由": {"command": "import-route direct", "description": "引入直连路由到BGP", "example": "[H3C-bgp-ipv4] import-route direct"},
            "引入静态路由": {"command": "import-route static", "description": "引入静态路由到BGP", "example": "[H3C-bgp-ipv4] import-route static"},
            "查看BGP邻居": {"command": "display bgp peer", "description": "查看BGP对等体状态", "example": "<H3C> display bgp peer"},
            "查看BGP路由": {"command": "display bgp routing-table ipv4", "description": "查看BGP路由表", "example": "<H3C> display bgp routing-table ipv4"}
        },
        "RIP配置": {
            "启用RIP进程": {"command": "rip <process-id>", "description": "启动RIP进程", "example": "[H3C] rip 1"},
            "宣告网络": {"command": "network <network>", "description": "宣告直连网络", "example": "[H3C-rip-1] network 192.168.0.0"},
            "设置RIP版本": {"command": "version <1|2>", "description": "设置RIP版本", "example": "[H3C-rip-1] version 2"},
            "关闭自动汇总": {"command": "undo summary", "description": "关闭RIP自动汇总", "example": "[H3C-rip-1] undo summary"},
            "配置被动接口": {"command": "silent-interface <interface>", "description": "禁止接口发送RIP报文", "example": "[H3C-rip-1] silent-interface Vlan-interface10"},
            "查看RIP路由": {"command": "display rip <process-id> route", "description": "查看RIP路由", "example": "<H3C> display rip 1 route"},
            "查看RIP数据库": {"command": "display rip <process-id> database", "description": "查看RIP数据库", "example": "<H3C> display rip 1 database"}
        }
    },
    "安全配置": {
        "ACL配置": {
            "创建基本ACL": {"command": "acl number <2000-2999>", "description": "创建基本ACL(2000-2999)", "example": "[H3C] acl number 2000"},
            "创建高级ACL": {"command": "acl number <3000-3999>", "description": "创建高级ACL(3000-3999)", "example": "[H3C] acl number 3000"},
            "创建命名ACL": {"command": "acl number <number> name <name>", "description": "创建命名ACL", "example": "[H3C] acl number 3000 name SERVER_ACL"},
            "基本规则": {"command": "rule <permit|deny> source <source> <wildcard>", "description": "配置基本ACL规则", "example": "[H3C-acl-basic-2000] rule permit source 192.168.1.0 0.0.0.255"},
            "高级规则": {"command": "rule <permit|deny> <protocol> source <src> <wildcard> destination <dst> <wildcard> [<port>]", "description": "配置高级ACL规则", "example": "[H3C-acl-adv-3000] rule permit tcp source 192.168.1.0 0.0.0.255 destination 10.0.0.1 0.0.0.0 destination-port eq 80"},
            "拒绝所有": {"command": "rule deny", "description": "拒绝所有流量", "example": "[H3C-acl-adv-3000] rule deny"},
            "允许所有": {"command": "rule permit", "description": "允许所有流量", "example": "[H3C-acl-adv-3000] rule permit"},
            "端口匹配": {"command": "destination-port eq <port>\ndestination-port range <start> <end>", "description": "匹配目标端口", "example": "[H3C-acl-adv-3000] rule permit tcp destination any destination-port eq 80"},
            "时间段ACL": {"command": "time-range <name> <start> to <end>", "description": "配置时间段", "example": "[H3C] time-range work-time 09:00 to 18:00 working-day\n[H3C-acl-adv-3000] rule permit tcp time-range work-time"},
            "接口应用ACL": {"command": "interface <interface>\npacket-filter <acl-number> <inbound|outbound>", "description": "在接口应用ACL过滤流量", "example": "[H3C-GigabitEthernet1/0/1] packet-filter 3000 inbound"},
            "查看ACL": {"command": "display acl <number>", "description": "查看ACL配置", "example": "<H3C> display acl 3000"}
        },
        "端口安全": {
            "启用端口安全": {"command": "port-security enable", "description": "启用端口安全功能", "example": "[H3C-GigabitEthernet1/0/1] port-security enable"},
            "最大MAC数": {"command": "port-security max-mac-count <number>", "description": "设置端口最大MAC地址数", "example": "[H3C-GigabitEthernet1/0/1] port-security max-mac-count 1"},
            "配置安全MAC": {"command": "port-security mac-address <mac> vlan <vlan-id>", "description": "手动配置安全MAC地址", "example": "[H3C-GigabitEthernet1/0/1] port-security mac-address 0001-0002-0003 vlan 10"},
            "自动学习MAC": {"command": "port-security port-mode sticky", "description": "启用粘性MAC自动学习", "example": "[H3C-GigabitEthernet1/0/1] port-security port-mode sticky"},
            "安全违规处理": {"command": "port-security intrusion-mode <blockmac|disableport>", "description": "设置违规处理方式", "example": "[H3C-GigabitEthernet1/0/1] port-security intrusion-mode disableport"},
            "查看端口安全": {"command": "display port-security interface <interface>", "description": "查看接口端口安全状态", "example": "<H3C> display port-security interface GigabitEthernet1/0/1"}
        },
        "DHCP Snooping": {
            "启用DHCP Snooping": {"command": "dhcp-snooping", "description": "全局启用DHCP Snooping", "example": "[H3C] dhcp-snooping"},
            "信任接口": {"command": "interface <interface>\ndhcp-snooping trust", "description": "配置DHCP信任接口", "example": "[H3C-GigabitEthernet1/0/24] dhcp-snooping trust"},
            "非信任接口检查": {"command": "interface <interface>\ndhcp-snooping check dhcp-chaddr enable", "description": "配置非信任接口检查", "example": "[H3C-GigabitEthernet1/0/1] dhcp-snooping check dhcp-chaddr enable"},
            "VLAN启用": {"command": "vlan <vlan-id>\ndhcp-snooping enable", "description": "在VLAN启用DHCP Snooping", "example": "[H3C-vlan10] dhcp-snooping enable"},
            "查看绑定表": {"command": "display dhcp-snooping", "description": "查看DHCP Snooping绑定表", "example": "<H3C> display dhcp-snooping"}
        },
        "ARP安全": {
            "静态ARP绑定": {"command": "arp static <ip> <mac> [interface <interface>]", "description": "配置静态ARP表项", "example": "[H3C] arp static 192.168.1.100 0001-0002-0003 interface GigabitEthernet 1/0/1"},
            "ARP检测": {"command": "arp detection enable", "description": "启用ARP检测", "example": "[H3C-vlan10] arp detection enable"},
            "查看ARP表": {"command": "display arp", "description": "查看ARP表", "example": "<H3C> display arp"},
            "清除ARP表": {"command": "reset arp dynamic", "description": "清除动态ARP表项", "example": "<H3C> reset arp dynamic"}
        },
        "IPSG配置": {
            "启用IPSG": {"command": "ip verify source ip-address mac-address", "description": "启用IP源防护", "example": "[H3C-GigabitEthernet1/0/1] ip verify source ip-address mac-address"},
            "静态绑定": {"command": "ip source static binding ip-address <ip> mac-address <mac>", "description": "配置静态IP/MAC绑定", "example": "[H3C-GigabitEthernet1/0/1] ip source static binding ip-address 192.168.1.100 mac-address 0001-0002-0003"}
        }
    },
    "生成树配置": {
        "STP基础": {
            "启用STP": {"command": "stp enable", "description": "全局启用STP", "example": "[H3C] stp enable"},
            "关闭STP": {"command": "stp disable", "description": "全局关闭STP", "example": "[H3C] stp disable"},
            "配置STP模式": {"command": "stp mode <stp|rstp|mstp>", "description": "设置STP模式", "example": "[H3C] stp mode mstp"},
            "设置桥优先级": {"command": "stp priority <priority>", "description": "设置网桥优先级(0-61440,步长4096)", "example": "[H3C] stp priority 4096"},
            "设置根桥": {"command": "stp root <primary|secondary>", "description": "设置为主/备根桥", "example": "[H3C] stp root primary"},
            "设置端口优先级": {"command": "interface <interface>\nstp priority <priority>", "description": "设置端口优先级", "example": "[H3C-GigabitEthernet1/0/1] stp priority 128"},
            "设置端口开销": {"command": "interface <interface>\nstp cost <cost>", "description": "设置端口开销", "example": "[H3C-GigabitEthernet1/0/1] stp cost 200000"},
            "启用端口边缘": {"command": "interface <interface>\nstp edged-port", "description": "配置边缘端口(立即转发)", "example": "[H3C-GigabitEthernet1/0/1] stp edged-port"},
            "BPDU保护": {"command": "stp bpdu-protection", "description": "启用BPDU保护", "example": "[H3C] stp bpdu-protection"},
            "根保护": {"command": "interface <interface>\nstp root-protection", "description": "配置根保护", "example": "[H3C-GigabitEthernet1/0/24] stp root-protection"},
            "环路保护": {"command": "interface <interface>\nstp loop-protection", "description": "配置环路保护", "example": "[H3C-GigabitEthernet1/0/1] stp loop-protection"},
            "查看STP状态": {"command": "display stp", "description": "查看STP状态", "example": "<H3C> display stp"},
            "查看STP端口": {"command": "display stp interface <interface>", "description": "查看端口STP状态", "example": "<H3C> display stp interface GigabitEthernet1/0/1"}
        },
        "MSTP配置": {
            "进入MST域": {"command": "stp region-configuration", "description": "进入MST域配置", "example": "[H3C] stp region-configuration"},
            "配置域名": {"command": "region-name <name>", "description": "设置MST域名", "example": "[H3C-mst-region] region-name MST_DOMAIN_1"},
            "配置实例映射": {"command": "instance <instance-id> vlan <vlan-id-list>", "description": "配置VLAN到实例映射", "example": "[H3C-mst-region] instance 1 vlan 10 20\n[H3C-mst-region] instance 2 vlan 30 40"},
            "配置修订级别": {"command": "revision-level <level>", "description": "设置MST修订级别", "example": "[H3C-mst-region] revision-level 1"},
            "激活MST域": {"command": "active region-configuration", "description": "激活MST域配置", "example": "[H3C-mst-region] active region-configuration"},
            "设置实例优先级": {"command": "stp instance <instance-id> priority <priority>", "description": "设置实例网桥优先级", "example": "[H3C] stp instance 1 priority 4096"},
            "设置实例根桥": {"command": "stp instance <instance-id> root <primary|secondary>", "description": "设置实例根桥", "example": "[H3C] stp instance 1 root primary"},
            "查看MST配置": {"command": "display stp region-configuration", "description": "查看MST域配置", "example": "<H3C> display stp region-configuration"}
        }
    },
    "高可用配置": {
        "VRRP配置": {
            "配置VRRP组": {"command": "interface Vlan-interface <vlan-id>\nvrrp vrid <vrid> virtual-ip <vip>", "description": "配置VRRP虚拟网关", "example": "[H3C-Vlan-interface10] vrrp vrid 1 virtual-ip 192.168.10.254"},
            "设置优先级": {"command": "vrrp vrid <vrid> priority <priority>", "description": "设置VRRP优先级", "example": "[H3C-Vlan-interface10] vrrp vrid 1 priority 120"},
            "配置抢占": {"command": "vrrp vrid <vrid> preempt-mode <timer delay>", "description": "配置抢占模式", "example": "[H3C-Vlan-interface10] vrrp vrid 1 preempt-mode timer delay 20"},
            "跟踪接口": {"command": "vrrp vrid <vrid> track interface <interface> reduced <value>", "description": "跟踪接口状态降低优先级", "example": "[H3C-Vlan-interface10] vrrp vrid 1 track interface GigabitEthernet1/0/1 reduced 30"},
            "认证配置": {"command": "vrrp vrid <vrid> authentication-mode <simple|md5> <password>", "description": "配置VRRP认证", "example": "[H3C-Vlan-interface10] vrrp vrid 1 authentication-mode md5 plain H3C@123"},
            "查看VRRP状态": {"command": "display vrrp", "description": "查看VRRP状态", "example": "<H3C> display vrrp"},
            "查看VRRP详细": {"command": "display vrrp verbose", "description": "查看VRRP详细信息", "example": "<H3C> display vrrp verbose"}
        },
        "IRF堆叠配置": {
            "配置IRF域": {"command": "irf domain <domain-id>", "description": "配置IRF域ID", "example": "[H3C] irf domain 10"},
            "配置IRF成员": {"command": "irf member <member-id> priority <priority>", "description": "设置IRF成员优先级", "example": "[H3C] irf member 1 priority 32"},
            "配置IRF端口": {"command": "irf-port <port-id>\nport group interface <interface>", "description": "配置IRF物理端口", "example": "[H3C] irf-port 1/1\n[H3C-irf-port1/1] port group interface GigabitEthernet1/0/47"},
            "激活IRF配置": {"command": "irf-port-configuration active", "description": "激活IRF配置", "example": "[H3C] irf-port-configuration active"},
            "查看IRF状态": {"command": "display irf", "description": "查看IRF状态", "example": "<H3C> display irf"},
            "查看IRF拓扑": {"command": "display irf topology", "description": "查看IRF拓扑", "example": "<H3C> display irf topology"},
            "IRF合并检测": {"command": "mad enable", "description": "启用MAD多Active检测", "example": "[H3C] mad enable"}
        },
        "BFD配置": {
            "启用BFD": {"command": "bfd", "description": "全局启用BFD", "example": "[H3C] bfd"},
            "创建BFD会话": {"command": "bfd <session-name> bind peer-interface <interface> source-ip <ip> destination-ip <ip>", "description": "创建BFD会话", "example": "[H3C] bfd session1 bind peer-interface GigabitEthernet1/0/1 source-ip 10.0.0.1 destination-ip 10.0.0.2"},
            "配置检测参数": {"command": "discriminator local <value>\ndiscriminator remote <value>", "description": "配置BFD参数", "example": "[H3C-bfd-session-session1] discriminator local 1\n[H3C-bfd-session-session1] discriminator remote 2"},
            "配置检测时间": {"command": "min-transmit-interval <ms>\nmin-receive-interval <ms>", "description": "配置检测时间间隔", "example": "[H3C-bfd-session-session1] min-transmit-interval 100\n[H3C-bfd-session-session1] min-receive-interval 100"},
            "查看BFD会话": {"command": "display bfd session", "description": "查看BFD会话", "example": "<H3C> display bfd session"}
        },
        "Track配置": {
            "创建Track项": {"command": "track <track-id> bfd singlehop session <session-name>", "description": "创建Track跟踪BFD", "example": "[H3C] track 1 bfd singlehop session session1"},
            "Track跟踪接口": {"command": "track <track-id> interface <interface>", "description": "Track跟踪接口状态", "example": "[H3C] track 1 interface GigabitEthernet1/0/1"},
            "查看Track状态": {"command": "display track", "description": "查看Track状态", "example": "<H3C> display track"}
        }
    },
    "管理与监控": {
        "日志配置": {
            "启用信息中心": {"command": "info-center enable", "description": "启用信息中心", "example": "[H3C] info-center enable"},
            "配置日志主机": {"command": "info-center loghost <ip>", "description": "配置日志服务器", "example": "[H3C] info-center loghost 192.168.1.100"},
            "配置日志级别": {"command": "info-center source <module> level <level>", "description": "配置日志级别", "example": "[H3C] info-center source default level informational"},
            "配置日志缓冲": {"command": "info-center logbuffer size <size>", "description": "配置日志缓冲区大小", "example": "[H3C] info-center logbuffer size 1024"},
            "启用终端显示": {"command": "terminal monitor\nterminal logging", "description": "终端显示日志", "example": "<H3C> terminal monitor\n<H3C> terminal logging"},
            "查看日志": {"command": "display logbuffer", "description": "查看日志缓冲区", "example": "<H3C> display logbuffer"},
            "清除日志": {"command": "reset logbuffer", "description": "清除日志缓冲区", "example": "<H3C> reset logbuffer"}
        },
        "SNMP配置": {
            "启用SNMP": {"command": "snmp-agent", "description": "启用SNMP Agent", "example": "[H3C] snmp-agent"},
            "设置SNMP版本": {"command": "snmp-agent sys-info version <v1|v2c|v3|all>", "description": "设置SNMP版本", "example": "[H3C] snmp-agent sys-info version v2c v3"},
            "配置只读共同体": {"command": "snmp-agent community read <community>", "description": "配置SNMP只读共同体", "example": "[H3C] snmp-agent community read public"},
            "配置读写共同体": {"command": "snmp-agent community write <community>", "description": "配置SNMP读写共同体", "example": "[H3C] snmp-agent community write private"},
            "配置Trap": {"command": "snmp-agent trap enable", "description": "启用Trap", "example": "[H3C] snmp-agent trap enable"},
            "配置Trap目标": {"command": "snmp-agent target-host trap address udp-domain <ip> params securityname <community>", "description": "配置Trap目标主机", "example": "[H3C] snmp-agent target-host trap address udp-domain 192.168.1.100 params securityname public"},
            "配置系统信息": {"command": "snmp-agent sys-info contact <contact>\nsnmp-agent sys-info location <location>", "description": "配置系统联系人/位置", "example": "[H3C] snmp-agent sys-info contact admin@company.com\n[H3C] snmp-agent sys-info location 'IDC_Room_A'"},
            "查看SNMP配置": {"command": "display snmp-agent sys-info", "description": "查看SNMP系统信息", "example": "<H3C> display snmp-agent sys-info"}
        },
        "NTP配置": {
            "启用NTP": {"command": "ntp-service enable", "description": "启用NTP服务", "example": "[H3C] ntp-service enable"},
            "配置NTP服务器": {"command": "ntp-service unicast-server <ip>", "description": "配置NTP服务器", "example": "[H3C] ntp-service unicast-server 192.168.1.100"},
            "配置时区": {"command": "clock timezone <name> <add|minus> <hours> [<minutes>]", "description": "配置时区", "example": "[H3C] clock timezone BJ add 08:00"},
            "查看NTP状态": {"command": "display ntp-service status", "description": "查看NTP状态", "example": "<H3C> display ntp-service status"},
            "查看NTP会话": {"command": "display ntp-service sessions", "description": "查看NTP会话", "example": "<H3C> display ntp-service sessions"}
        },
        "NetStream配置": {
            "启用NetStream": {"command": "ip netstream timeout active <minutes>", "description": "配置NetStream超时", "example": "[H3C] ip netstream timeout active 10"},
            "接口启用": {"command": "interface <interface>\nip netstream <inbound|outbound>", "description": "接口启用NetStream", "example": "[H3C-GigabitEthernet1/0/1] ip netstream inbound"},
            "配置输出目标": {"command": "ip netstream export host <ip> <port>", "description": "配置NetStream输出目标", "example": "[H3C] ip netstream export host 192.168.1.100 9996"},
            "查看统计": {"command": "display ip netstream cache", "description": "查看NetStream缓存", "example": "<H3C> display ip netstream cache"}
        }
    },
    "QoS配置": {
        "优先级映射": {
            "配置信任DSCP": {"command": "interface <interface>\nqos trust dscp", "description": "信任DSCP优先级", "example": "[H3C-GigabitEthernet1/0/1] qos trust dscp"},
            "配置信任802.1p": {"command": "interface <interface>\nqos trust dot1p", "description": "信任802.1p优先级", "example": "[H3C-GigabitEthernet1/0/1] qos trust dot1p"},
            "配置端口优先级": {"command": "interface <interface>\nqos priority <priority>", "description": "设置端口优先级", "example": "[H3C-GigabitEthernet1/0/1] qos priority 5"}
        },
        "流量整形": {
            "接口限速": {"command": "interface <interface>\nqos lr <inbound|outbound> cir <kbps>", "description": "接口限速", "example": "[H3C-GigabitEthernet1/0/1] qos lr outbound cir 10000"},
            "队列整形": {"command": "interface <interface>\nqos queue <queue-id> cir <kbps>", "description": "队列流量整形", "example": "[H3C-GigabitEthernet1/0/1] qos queue 0 cir 5000"}
        },
        "拥塞管理": {
            "配置SP队列": {"command": "interface <interface>\nqos sp", "description": "配置严格优先级调度", "example": "[H3C-GigabitEthernet1/0/1] qos sp"},
            "配置WRR队列": {"command": "interface <interface>\nqos wrr queue <queue-id> weight <weight>", "description": "配置WRR调度权重", "example": "[H3C-GigabitEthernet1/0/1] qos wrr queue 0 weight 10"}
        }
    },
    "IPv6配置": {
        "基础配置": {
            "启用IPv6": {"command": "ipv6", "description": "全局启用IPv6", "example": "[H3C] ipv6"},
            "接口IPv6地址": {"command": "interface <interface>\nipv6 address <ipv6>/<prefix>", "description": "配置接口IPv6地址", "example": "[H3C-GigabitEthernet1/0/1] ipv6 address 2001:db8::1/64"},
            "自动配置地址": {"command": "ipv6 address auto link-local", "description": "自动配置链路本地地址", "example": "[H3C-GigabitEthernet1/0/1] ipv6 address auto link-local"},
            "查看IPv6接口": {"command": "display ipv6 interface <interface>", "description": "查看接口IPv6信息", "example": "<H3C> display ipv6 interface GigabitEthernet1/0/1"},
            "查看IPv6路由": {"command": "display ipv6 routing-table", "description": "查看IPv6路由表", "example": "<H3C> display ipv6 routing-table"},
            "Ping IPv6": {"command": "ping ipv6 <ipv6>", "description": "测试IPv6连通性", "example": "<H3C> ping ipv6 2001:db8::1"}
        },
        "IPv6路由": {
            "静态路由": {"command": "ipv6 route-static <dest>/<prefix> <next-hop>", "description": "配置IPv6静态路由", "example": "[H3C] ipv6 route-static ::/0 2001:db8::ffff"},
            "OSPFv3": {"command": "ospfv3 <process-id>\nrouter-id <router-id>\narea <area-id>", "description": "配置OSPFv3", "example": "[H3C] ospfv3 1\n[H3C-ospfv3-1] router-id 1.1.1.1\n[H3C-ospfv3-1] area 0"}
        }
    }
}

H3C_CASES = [
    {
        "title": "接入交换机基础配置",
        "description": "接入层交换机初始化配置，包括VLAN、管理IP、SSH、端口安全",
        "steps": [
            "# 1. 系统基本配置",
            "sysname Access-SW-01",
            "",
            "# 2. 创建VLAN",
            "vlan 10",
            " name Sales",
            "vlan 20",
            " name Engineering",
            "vlan 30",
            " name Finance",
            "vlan 100",
            " name Management",
            "",
            "# 3. 配置VLAN接口",
            "interface Vlan-interface 100",
            " ip address 192.168.100.1 255.255.255.0",
            "",
            "# 4. 配置管理IP",
            "interface Vlan-interface 1",
            " ip address 192.168.1.10 255.255.255.0",
            "",
            "# 5. 配置默认网关",
            "ip route-static 0.0.0.0 0 192.168.1.254",
            "",
            "# 6. 配置Access端口",
            "interface GigabitEthernet 1/0/1",
            " port link-type access",
            " port access vlan 10",
            " description Sales_PC_01",
            "",
            "interface GigabitEthernet 1/0/2",
            " port link-type access",
            " port access vlan 20",
            " description Engineering_PC_01",
            "",
            "# 7. 配置Trunk上行口",
            "interface GigabitEthernet 1/0/24",
            " port link-type trunk",
            " port trunk permit vlan 10 20 30 100",
            " description Uplink_to_Core",
            "",
            "# 8. 配置SSH",
            "public-key local create rsa",
            "ssh server enable",
            "",
            "local-user admin",
            " password simple Admin@123",
            " authorization-attribute level 3",
            " service-type ssh",
            "",
            "user-interface vty 0 4",
            " authentication-mode scheme",
            " protocol inbound ssh",
            "",
            "# 9. 配置端口安全",
            "interface GigabitEthernet 1/0/1",
            " port-security enable",
            " port-security max-mac-count 2",
            " port-security intrusion-mode disableport",
            "",
            "# 10. 配置STP边缘端口",
            "interface GigabitEthernet 1/0/1",
            " stp edged-port",
            "",
            "# 11. 保存配置",
            "save"
        ]
    },
    {
        "title": "核心交换机配置",
        "description": "核心交换机完整配置，包括VLANIF、路由、ACL、VRRP",
        "steps": [
            "# 1. 系统配置",
            "sysname Core-SW-01",
            "",
            "# 2. 创建VLAN",
            "vlan 10 20 30 100 200",
            "",
            "# 3. 配置VLAN接口",
            "interface Vlan-interface 10",
            " ip address 192.168.10.1 255.255.255.0",
            " description Gateway_VLAN10_Sales",
            "",
            "interface Vlan-interface 20",
            " ip address 192.168.20.1 255.255.255.0",
            " description Gateway_VLAN20_Engineering",
            "",
            "interface Vlan-interface 30",
            " ip address 192.168.30.1 255.255.255.0",
            " description Gateway_VLAN30_Finance",
            "",
            "interface Vlan-interface 100",
            " ip address 192.168.100.1 255.255.255.0",
            " description Management_Network",
            "",
            "interface Vlan-interface 200",
            " ip address 10.0.0.1 255.255.255.252",
            " description WAN_Uplink",
            "",
            "# 4. 配置DHCP",
            "dhcp enable",
            "dhcp server ip-pool vlan10_pool",
            " network 192.168.10.0 mask 255.255.255.0",
            " gateway-list 192.168.10.1",
            " dns-list 8.8.8.8 114.114.114.114",
            "",
            "interface Vlan-interface 10",
            " dhcp select server",
            "",
            "# 5. 配置静态路由",
            "ip route-static 0.0.0.0 0 10.0.0.2",
            "",
            "# 6. 配置OSPF",
            "ospf 1 router-id 1.1.1.1",
            " area 0.0.0.0",
            "  network 192.168.0.0 0.0.255.255",
            "  network 10.0.0.0 0.0.0.3",
            "",
            "# 7. 配置ACL",
            "acl number 3000",
            " rule 0 deny ip source 192.168.20.0 0.0.0.255 destination 192.168.30.0 0.0.0.255",
            " rule 5 permit ip",
            "",
            "interface Vlan-interface 20",
            " packet-filter 3000 outbound",
            "",
            "# 8. 配置VRRP",
            "interface Vlan-interface 10",
            " vrrp vrid 1 virtual-ip 192.168.10.254",
            " vrrp vrid 1 priority 120",
            " vrrp vrid 1 preempt-mode timer delay 20",
            "",
            "# 9. 配置NTP",
            "ntp-service enable",
            "ntp-service unicast-server 192.168.100.100",
            "clock timezone BJ add 08:00",
            "",
            "# 10. 配置日志",
            "info-center enable",
            "info-center loghost 192.168.100.101",
            "",
            "# 11. 配置SNMP",
            "snmp-agent",
            "snmp-agent sys-info version v2c",
            "snmp-agent community read Public@123",
            "snmp-agent sys-info contact admin@company.com",
            "",
            "save"
        ]
    },
    {
        "title": "链路聚合配置",
        "description": "H3C链路聚合配置，LACP动态模式",
        "steps": [
            "# 1. 创建聚合接口",
            "interface Bridge-Aggregation 1",
            " description To_Core_Switch",
            " port link-type trunk",
            " port trunk permit vlan 10 20 30",
            " link-aggregation mode dynamic",
            "",
            "# 2. 添加成员接口",
            "interface GigabitEthernet 1/0/1",
            " port link-aggregation group 1",
            "",
            "interface GigabitEthernet 1/0/2",
            " port link-aggregation group 1",
            "",
            "interface GigabitEthernet 1/0/3",
            " port link-aggregation group 1",
            "",
            "# 3. 配置LACP优先级(可选)",
            "lacp system-priority 100",
            "",
            "# 4. 验证配置",
            "display link-aggregation summary",
            "display link-aggregation verbose"
        ]
    },
    {
        "title": "MSTP多生成树配置",
        "description": "MSTP多实例生成树配置，实现负载均衡",
        "steps": [
            "# 1. 配置MSTP域",
            "stp region-configuration",
            " region-name COMPANY_MST",
            " revision-level 1",
            " instance 1 vlan 10 20",
            " instance 2 vlan 30 40",
            " active region-configuration",
            "",
            "# 2. 配置STP模式",
            "stp mode mstp",
            "",
            "# 3. 核心交换机1配置",
            "stp instance 1 root primary",
            "stp instance 2 root secondary",
            "",
            "# 4. 核心交换机2配置",
            "stp instance 1 root secondary",
            "stp instance 2 root primary",
            "",
            "# 5. 启用BPDU保护",
            "stp bpdu-protection",
            "",
            "# 6. 配置边缘端口",
            "interface GigabitEthernet 1/0/1",
            " stp edged-port",
            "",
            "# 7. 验证配置",
            "display stp region-configuration",
            "display stp instance 1",
            "display stp instance 2"
        ]
    },
    {
        "title": "IRF堆叠配置",
        "description": "H3C IRF智能弹性架构配置",
        "steps": [
            "# 交换机1配置",
            "# 1. 设置IRF成员编号和优先级",
            "irf member 1 priority 32",
            "",
            "# 2. 配置IRF端口",
            "irf-port 1/1",
            " port group interface GigabitEthernet 1/0/47",
            " port group interface GigabitEthernet 1/0/48",
            "",
            "# 3. 激活IRF配置",
            "irf-port-configuration active",
            "",
            "# 交换机2配置(先不连接IRF线)",
            "# 1. 修改成员编号",
            "irf member 1 renumber 2",
            "",
            "# 2. 重启后配置",
            "irf member 2 priority 30",
            "",
            "irf-port 2/1",
            " port group interface GigabitEthernet 2/0/47",
            " port group interface GigabitEthernet 2/0/48",
            "",
            "irf-port-configuration active",
            "",
            "# 4. MAD配置(多Active检测)",
            "mad enable",
            "mad bfd enable",
            "",
            "# 5. 验证配置",
            "display irf",
            "display irf topology",
            "display irf configuration"
        ]
    },
    {
        "title": "DHCP服务器配置",
        "description": "交换机作为DHCP服务器配置",
        "steps": [
            "# 1. 启用DHCP服务",
            "dhcp enable",
            "",
            "# 2. 配置地址池",
            "dhcp server ip-pool vlan10_pool",
            " network 192.168.10.0 mask 255.255.255.0",
            " gateway-list 192.168.10.1",
            " dns-list 8.8.8.8 114.114.114.114",
            " excluded-ip-address 192.168.10.1 192.168.10.10",
            " expired day 3",
            "",
            "dhcp server ip-pool vlan20_pool",
            " network 192.168.20.0 mask 255.255.255.0",
            " gateway-list 192.168.20.1",
            " dns-list 8.8.8.8",
            " expired day 7",
            "",
            "# 3. 在VLAN接口启用DHCP",
            "interface Vlan-interface 10",
            " dhcp select server",
            "",
            "interface Vlan-interface 20",
            " dhcp select server",
            "",
            "# 4. 配置DHCP中继(如需要)",
            "interface Vlan-interface 30",
            " dhcp select relay",
            " dhcp relay server-address 192.168.100.100",
            "",
            "# 5. 查看DHCP配置",
            "display dhcp server ip-in-use",
            "display dhcp server statistics"
        ]
    },
    {
        "title": "QoS流量限速配置",
        "description": "基于ACL的流量限速配置",
        "steps": [
            "# 1. 创建ACL匹配流量",
            "acl number 3000",
            " rule 0 permit ip source 192.168.10.0 0.0.0.255",
            "",
            "# 2. 创建流分类",
            "traffic classifier CLASS_LIMIT",
            " if-match acl 3000",
            "",
            "# 3. 创建流行为",
            "traffic behavior BEHAV_LIMIT",
            " car cir 10000 pir 20000 green pass yellow pass red discard",
            "",
            "# 4. 创建流策略",
            "traffic policy POLICY_LIMIT",
            " classifier CLASS_LIMIT behavior BEHAV_LIMIT",
            "",
            "# 5. 应用流策略",
            "interface GigabitEthernet 1/0/1",
            " qos apply policy POLICY_LIMIT inbound",
            "",
            "# 6. 验证配置",
            "display traffic policy"
        ]
    },
    {
        "title": "端口镜像配置",
        "description": "配置端口镜像用于流量监控",
        "steps": [
            "# 1. 创建镜像组",
            "mirroring-group 1 local",
            "",
            "# 2. 配置观察端口",
            "mirroring-group 1 monitor-port GigabitEthernet 1/0/24",
            "",
            "# 3. 配置镜像端口(镜像所有流量)",
            "mirroring-group 1 mirroring-port GigabitEthernet 1/0/1 both",
            "",
            "# 4. 配置镜像端口(只镜像入方向)",
            "mirroring-group 1 mirroring-port GigabitEthernet 1/0/2 inbound",
            "",
            "# 5. 验证配置",
            "display mirroring-group all"
        ]
    },
    {
        "title": "BFD与Track联动VRRP",
        "description": "BFD检测链路故障联动VRRP快速切换",
        "steps": [
            "# 1. 启用BFD",
            "bfd",
            "",
            "# 2. 创建BFD会话",
            "bfd vrrp_bfd bind peer-interface GigabitEthernet 1/0/1 source-ip 192.168.1.1 destination-ip 192.168.1.2",
            " discriminator local 1",
            " discriminator remote 2",
            " min-transmit-interval 100",
            " min-receive-interval 100",
            "",
            "# 3. 创建Track项",
            "track 1 bfd singlehop session vrrp_bfd",
            "",
            "# 4. VRRP联动Track",
            "interface Vlan-interface 10",
            " vrrp vrid 1 virtual-ip 192.168.10.254",
            " vrrp vrid 1 priority 120",
            " vrrp vrid 1 track 1 reduced 40",
            "",
            "# 5. 验证配置",
            "display bfd session",
            "display track",
            "display vrrp"
        ]
    }
]
