#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
华为交换机命令手册 - 完整版
"""

HUAWEI_COMMANDS = {
    "基础配置": {
        "系统管理": {
            "进入系统视图": {"command": "system-view", "description": "从用户视图进入系统视图", "example": "<Huawei> system-view\n[Huawei]"},
            "修改设备名称": {"command": "sysname <name>", "description": "设置交换机主机名", "example": "[Huawei] sysname SW-Core\n[SW-Core]"},
            "显示当前配置": {"command": "display current-configuration", "description": "查看当前运行配置", "example": "[Huawei] display current-configuration"},
            "显示保存配置": {"command": "display saved-configuration", "description": "查看已保存的配置", "example": "[Huawei] display saved-configuration"},
            "保存配置": {"command": "save", "description": "保存当前配置到存储器", "example": "<Huawei> save"},
            "重启设备": {"command": "reboot", "description": "重启交换机", "example": "<Huawei> reboot"},
            "恢复出厂配置": {"command": "reset saved-configuration\nreboot", "description": "清除配置并重启恢复出厂", "example": "<Huawei> reset saved-configuration\n<Huawei> reboot"},
            "查看系统信息": {"command": "display version", "description": "查看设备版本和硬件信息", "example": "<Huawei> display version"},
            "配置系统时间": {"command": "clock datetime <HH:MM:SS> <YYYY-MM-DD>", "description": "设置系统时间", "example": "<Huawei> clock datetime 14:30:00 2024-01-15"},
            "查看系统资源": {"command": "display cpu-usage\ndisplay memory-usage", "description": "查看CPU和内存使用率", "example": "<Huawei> display cpu-usage"},
            "配置闲置超时": {"command": "idle-timeout <minutes>", "description": "设置用户界面闲置超时时间", "example": "[Huawei] user-interface console 0\n[Huawei-ui-console0] idle-timeout 30"}
        },
        "用户与权限管理": {
            "创建本地用户": {"command": "local-user <username>", "description": "创建本地用户账号", "example": "[Huawei] local-user admin"},
            "设置用户密码": {"command": "password <cipher|irreversible-cipher> <password>", "description": "设置用户密码(cipher密文/irreversible-cipher不可逆加密)", "example": "[Huawei-luser-admin] password cipher Admin@123"},
            "设置用户权限级别": {"command": "level <0-15>", "description": "设置用户权限级别(0访客,1监控,3系统,15管理)", "example": "[Huawei-luser-admin] level 15"},
            "设置用户服务类型": {"command": "service-type <ssh|telnet|terminal|http|ftp>", "description": "设置用户允许的服务类型", "example": "[Huawei-luser-admin] service-type ssh telnet"},
            "设置超级密码": {"command": "super password <cipher> <password>", "description": "设置切换用户级别密码", "example": "[Huawei] super password cipher Super@123"},
            "配置AAA认证": {"command": "aaa\nauthentication-scheme <name>", "description": "配置AAA认证方案", "example": "[Huawei] aaa\n[Huawei-aaa] authentication-scheme default"},
            "用户界面配置": {"command": "user-interface <console|vty> <number>", "description": "进入用户界面配置", "example": "[Huawei] user-interface vty 0 4"},
            "设置登录认证方式": {"command": "authentication-mode <aaa|password|none>", "description": "设置用户界面认证模式", "example": "[Huawei-ui-vty0-4] authentication-mode aaa"},
            "查看在线用户": {"command": "display users", "description": "查看当前登录用户", "example": "<Huawei> display users"},
            "强制踢出用户": {"command": "free user-interface <type> <number>", "description": "强制断开指定用户连接", "example": "<Huawei> free user-interface vty 1"}
        },
        "SSH配置": {
            "生成RSA密钥": {"command": "rsa local-key-pair create", "description": "生成本地RSA密钥对", "example": "[Huawei] rsa local-key-pair create\nInput the bits in the modulus[default = 512]: 2048"},
            "启用SSH服务": {"command": "stelnet server enable", "description": "启用SSH服务器", "example": "[Huawei] stelnet server enable"},
            "设置SSH版本": {"command": "ssh server version <v1|v2|all>", "description": "设置SSH协议版本", "example": "[Huawei] ssh server version v2"},
            "创建SSH用户": {"command": "ssh user <username> authentication-type <password|rsa|all>", "description": "创建SSH用户并设置认证方式", "example": "[Huawei] ssh user admin authentication-type password"},
            "SSH用户服务类型": {"command": "ssh user <username> service-type <stelnet|sftp|all>", "description": "设置SSH用户服务类型", "example": "[Huawei] ssh user admin service-type stelnet"},
            "配置SSH超时": {"command": "ssh server timeout <seconds>", "description": "设置SSH连接超时时间", "example": "[Huawei] ssh server timeout 60"},
            "配置SSH重试次数": {"command": "ssh server authentication-retries <times>", "description": "设置SSH认证重试次数", "example": "[Huawei] ssh server authentication-retries 3"},
            "配置VTY允许SSH": {"command": "user-interface vty 0 4\nprotocol inbound ssh", "description": "VTY只允许SSH连接", "example": "[Huawei] user-interface vty 0 4\n[Huawei-ui-vty0-4] protocol inbound ssh"},
            "查看SSH状态": {"command": "display ssh server status\ndisplay ssh user-information", "description": "查看SSH服务状态和用户信息", "example": "<Huawei> display ssh server status"},
            "首次登录免确认": {"command": "ssh client first-time enable", "description": "SSH客户端首次登录不检查密钥", "example": "[Huawei] ssh client first-time enable"}
        },
        "Telnet配置": {
            "启用Telnet服务": {"command": "telnet server enable", "description": "启用Telnet服务器(不建议)", "example": "[Huawei] telnet server enable"},
            "配置VTY允许Telnet": {"command": "user-interface vty 0 4\nprotocol inbound telnet", "description": "VTY允许Telnet连接", "example": "[Huawei] user-interface vty 0 4\n[Huawei-ui-vty0-4] protocol inbound telnet"},
            "设置Telnet端口": {"command": "telnet server port <port>", "description": "修改Telnet服务端口(默认23)", "example": "[Huawei] telnet server port 2323"},
            "关闭Telnet服务": {"command": "undo telnet server enable", "description": "关闭Telnet服务提高安全性", "example": "[Huawei] undo telnet server enable"}
        },
        "Console配置": {
            "配置Console密码": {"command": "user-interface console 0\nauthentication-mode password\nset authentication password cipher <password>", "description": "设置Console登录密码", "example": "[Huawei] user-interface console 0\n[Huawei-ui-console0] authentication-mode password\n[Huawei-ui-console0] set authentication password cipher Console@123"},
            "Console认证模式": {"command": "authentication-mode <aaa|password|none>", "description": "设置Console认证模式", "example": "[Huawei-ui-console0] authentication-mode aaa"},
            "Console波特率": {"command": "speed <baud-rate>", "description": "设置Console波特率", "example": "[Huawei-ui-console0] speed 115200"}
        },
        "域名解析": {
            "配置DNS服务器": {"command": "ip dns server <ip> [priority]", "description": "配置DNS服务器地址", "example": "[Huawei] ip dns server 8.8.8.8\n[Huawei] ip dns server 114.114.114.114 priority 2"},
            "配置域名后缀": {"command": "ip domain <domain-name>", "description": "配置默认域名后缀", "example": "[Huawei] ip domain example.com"},
            "启用DNS解析": {"command": "ip dns resolve", "description": "启用DNS域名解析功能", "example": "[Huawei] ip dns resolve"},
            "静态DNS映射": {"command": "ip host <hostname> <ip>", "description": "配置静态主机名解析", "example": "[Huawei] ip host server1 192.168.1.100"},
            "测试DNS解析": {"command": "ping <hostname>", "description": "测试域名解析", "example": "<Huawei> ping www.google.com"}
        }
    },
    "接口配置": {
        "以太网接口": {
            "进入接口视图": {"command": "interface <interface-type> <interface-number>", "description": "进入指定接口配置视图", "example": "[Huawei] interface GigabitEthernet 0/0/1\n[Huawei-GigabitEthernet0/0/1]"},
            "接口描述": {"command": "description <text>", "description": "为接口添加描述信息", "example": "[Huawei-GigabitEthernet0/0/1] description To_Server_Room"},
            "开启接口": {"command": "undo shutdown", "description": "开启接口", "example": "[Huawei-GigabitEthernet0/0/1] undo shutdown"},
            "关闭接口": {"command": "shutdown", "description": "关闭接口", "example": "[Huawei-GigabitEthernet0/0/1] shutdown"},
            "配置接口IP": {"command": "ip address <ip> <mask> [sub]", "description": "配置接口IP地址", "example": "[Huawei-GigabitEthernet0/0/1] ip address 192.168.1.1 255.255.255.0"},
            "配置从IP": {"command": "ip address <ip> <mask> sub", "description": "配置接口从IP地址", "example": "[Huawei-GigabitEthernet0/0/1] ip address 192.168.2.1 255.255.255.0 sub"},
            "删除接口IP": {"command": "undo ip address", "description": "删除接口IP地址", "example": "[Huawei-GigabitEthernet0/0/1] undo ip address"},
            "设置接口速率": {"command": "speed <10|100|1000|auto>", "description": "设置接口速率", "example": "[Huawei-GigabitEthernet0/0/1] speed 1000"},
            "设置双工模式": {"command": "duplex <half|full|auto>", "description": "设置接口双工模式", "example": "[Huawei-GigabitEthernet0/0/1] duplex full"},
            "接口流量统计": {"command": "statistic enable", "description": "启用接口流量统计", "example": "[Huawei-GigabitEthernet0/0/1] statistic enable"},
            "查看接口状态": {"command": "display interface <interface>", "description": "查看接口详细状态", "example": "<Huawei> display interface GigabitEthernet0/0/1"},
            "查看接口简要": {"command": "display interface brief", "description": "查看所有接口简要状态", "example": "<Huawei> display interface brief"},
            "批量配置接口": {"command": "interface range <interface-list>", "description": "批量进入多个接口", "example": "[Huawei] interface range GigabitEthernet 0/0/1 to GigabitEthernet 0/0/10"},
            "接口环回检测": {"command": "loopback detect enable", "description": "启用接口环回检测", "example": "[Huawei-GigabitEthernet0/0/1] loopback detect enable"}
        },
        "VLAN接口": {
            "创建VLAN": {"command": "vlan <vlan-id>", "description": "创建VLAN", "example": "[Huawei] vlan 10"},
            "批量创建VLAN": {"command": "vlan batch <vlan-id-list>", "description": "批量创建多个VLAN", "example": "[Huawei] vlan batch 10 20 30 to 40"},
            "VLAN命名": {"command": "name <vlan-name>", "description": "为VLAN设置名称", "example": "[Huawei-vlan10] name Sales_Department"},
            "删除VLAN": {"command": "undo vlan <vlan-id>", "description": "删除指定VLAN", "example": "[Huawei] undo vlan 10"},
            "查看VLAN": {"command": "display vlan", "description": "查看所有VLAN信息", "example": "<Huawei> display vlan"},
            "查看指定VLAN": {"command": "display vlan <vlan-id>", "description": "查看指定VLAN详细信息", "example": "<Huawei> display vlan 10"},
            "创建VLANIF接口": {"command": "interface vlanif <vlan-id>", "description": "创建VLAN三层接口", "example": "[Huawei] interface Vlanif 10"},
            "VLANIF配置IP": {"command": "interface vlanif <vlan-id>\nip address <ip> <mask>", "description": "为VLANIF配置IP地址", "example": "[Huawei] interface Vlanif 10\n[Huawei-Vlanif10] ip address 192.168.10.1 255.255.255.0"},
            "VLANIF描述": {"command": "description <text>", "description": "为VLANIF添加描述", "example": "[Huawei-Vlanif10] description Gateway_for_VLAN10"}
        },
        "接口VLAN": {
            "Access接口": {"command": "port link-type access\nport default vlan <vlan-id>", "description": "配置接口为Access模式并加入VLAN", "example": "[Huawei-GigabitEthernet0/0/1] port link-type access\n[Huawei-GigabitEthernet0/0/1] port default vlan 10"},
            "Trunk接口": {"command": "port link-type trunk\nport trunk allow-pass vlan <vlan-id-list>", "description": "配置接口为Trunk模式", "example": "[Huawei-GigabitEthernet0/0/24] port link-type trunk\n[Huawei-GigabitEthernet0/0/24] port trunk allow-pass vlan 10 20 30"},
            "Trunk允许所有VLAN": {"command": "port trunk allow-pass vlan all", "description": "Trunk允许所有VLAN通过", "example": "[Huawei-GigabitEthernet0/0/24] port trunk allow-pass vlan all"},
            "Trunk Native VLAN": {"command": "port trunk pvid vlan <vlan-id>", "description": "设置Trunk接口PVID", "example": "[Huawei-GigabitEthernet0/0/24] port trunk pvid vlan 99"},
            "Hybrid接口": {"command": "port link-type hybrid", "description": "配置接口为Hybrid模式", "example": "[Huawei-GigabitEthernet0/0/1] port link-type hybrid"},
            "Hybrid Untagged": {"command": "port hybrid untagged vlan <vlan-id-list>", "description": "Hybrid接口剥离VLAN标签", "example": "[Huawei-GigabitEthernet0/0/1] port hybrid untagged vlan 10 20"},
            "Hybrid Tagged": {"command": "port hybrid tagged vlan <vlan-id-list>", "description": "Hybrid接口保留VLAN标签", "example": "[Huawei-GigabitEthernet0/0/1] port hybrid tagged vlan 100"},
            "Hybrid PVID": {"command": "port hybrid pvid vlan <vlan-id>", "description": "设置Hybrid接口PVID", "example": "[Huawei-GigabitEthernet0/0/1] port hybrid pvid vlan 10"},
            "QinQ配置": {"command": "port link-type dot1q-tunnel\nport default vlan <vlan-id>", "description": "配置QinQ端口", "example": "[Huawei-GigabitEthernet0/0/1] port link-type dot1q-tunnel\n[Huawei-GigabitEthernet0/0/1] port default vlan 100"}
        },
        "链路聚合": {
            "创建Eth-Trunk": {"command": "interface eth-trunk <trunk-id>", "description": "创建链路聚合接口", "example": "[Huawei] interface Eth-Trunk 1"},
            "配置聚合模式": {"command": "mode <lacp-static|lacp-dynamic|manual>", "description": "设置链路聚合模式", "example": "[Huawei-Eth-Trunk1] mode lacp-static"},
            "成员接口加入": {"command": "interface <interface>\neth-trunk <trunk-id>", "description": "将物理接口加入聚合组", "example": "[Huawei-GigabitEthernet0/0/1] eth-trunk 1"},
            "批量加入成员": {"command": "eth-trunk <trunk-id>\ninterface range <interface-list>", "description": "批量将接口加入聚合组", "example": "[Huawei] interface range GigabitEthernet 0/0/1 to GigabitEthernet 0/0/4\n[Huawei-port-group] eth-trunk 1"},
            "设置最大活跃链路": {"command": "max active-linknumber <number>", "description": "设置最大活跃链路数(LACP模式)", "example": "[Huawei-Eth-Trunk1] max active-linknumber 4"},
            "设置最小活跃链路": {"command": "least active-linknumber <number>", "description": "设置最小活跃链路数", "example": "[Huawei-Eth-Trunk1] least active-linknumber 2"},
            "配置负载均衡": {"command": "load-balance <src-dst-mac|src-dst-ip|dst-mac|dst-ip|src-mac|src-ip>", "description": "设置负载均衡算法", "example": "[Huawei-Eth-Trunk1] load-balance src-dst-ip"},
            "查看聚合状态": {"command": "display eth-trunk <trunk-id>", "description": "查看链路聚合状态", "example": "<Huawei> display eth-trunk 1"},
            "查看所有聚合": {"command": "display eth-trunk", "description": "查看所有链路聚合", "example": "<Huawei> display eth-trunk"},
            "LACP优先级": {"command": "lacp priority <priority>", "description": "设置LACP系统优先级", "example": "[Huawei] lacp priority 100"}
        }
    },
    "路由配置": {
        "静态路由": {
            "配置静态路由": {"command": "ip route-static <dest-network> <mask> <next-hop> [preference]", "description": "配置静态路由", "example": "[Huawei] ip route-static 192.168.100.0 255.255.255.0 10.0.0.1"},
            "默认路由": {"command": "ip route-static 0.0.0.0 0.0.0.0 <gateway>", "description": "配置默认路由", "example": "[Huawei] ip route-static 0.0.0.0 0.0.0.0 192.168.1.254"},
            "配置路由优先级": {"command": "ip route-static <dest> <mask> <next-hop> preference <preference>", "description": "设置静态路由优先级", "example": "[Huawei] ip route-static 10.0.0.0 24 192.168.1.1 preference 10"},
            "路由标记": {"command": "ip route-static <dest> <mask> <next-hop> tag <tag>", "description": "为路由设置标记", "example": "[Huawei] ip route-static 192.168.0.0 16 10.0.0.1 tag 100"},
            "黑洞路由": {"command": "ip route-static <dest> <mask> NULL0", "description": "配置黑洞路由丢弃流量", "example": "[Huawei] ip route-static 10.10.0.0 24 NULL0"},
            "删除静态路由": {"command": "undo ip route-static <dest> <mask> <next-hop>", "description": "删除指定静态路由", "example": "[Huawei] undo ip route-static 192.168.100.0 255.255.255.0 10.0.0.1"},
            "查看路由表": {"command": "display ip routing-table", "description": "查看IP路由表", "example": "<Huawei> display ip routing-table"},
            "查看静态路由": {"command": "display ip routing-table protocol static", "description": "只查看静态路由", "example": "<Huawei> display ip routing-table protocol static"},
            "路由追踪": {"command": "tracert <ip>", "description": "追踪到目标的路径", "example": "<Huawei> tracert 8.8.8.8"}
        },
        "OSPF配置": {
            "启用OSPF进程": {"command": "ospf <process-id> [router-id <router-id>]", "description": "启动OSPF进程", "example": "[Huawei] ospf 1 router-id 1.1.1.1"},
            "进入区域配置": {"command": "area <area-id>", "description": "进入OSPF区域配置", "example": "[Huawei-ospf-1] area 0"},
            "宣告网络": {"command": "network <network> <wildcard>", "description": "宣告直连网络到OSPF", "example": "[Huawei-ospf-1-area-0.0.0.0] network 192.168.0.0 0.0.255.255"},
            "配置区域类型": {"command": "area <area-id>\nnssa|stub [no-summary]", "description": "配置NSSA或Stub区域", "example": "[Huawei-ospf-1-area-0.0.0.1] nssa no-summary"},
            "设置OSPF优先级": {"command": "preference <preference>", "description": "设置OSPF路由优先级", "example": "[Huawei-ospf-1] preference 10"},
            "配置被动接口": {"command": "silent-interface <interface>", "description": "禁止接口发送OSPF报文", "example": "[Huawei-ospf-1] silent-interface Vlanif10"},
            "配置OSPF认证": {"command": "area <area-id>\nauthentication-mode simple <password>", "description": "配置区域认证", "example": "[Huawei-ospf-1-area-0.0.0.0] authentication-mode simple Huawei@123"},
            "配置接口认证": {"command": "interface <interface>\nospf authentication-mode <md5|simple> <password>", "description": "配置接口级OSPF认证", "example": "[Huawei-GigabitEthernet0/0/1] ospf authentication-mode md5 1 cipher Huawei@123"},
            "设置DR优先级": {"command": "interface <interface>\nospf dr-priority <priority>", "description": "设置接口DR选举优先级", "example": "[Huawei-GigabitEthernet0/0/1] ospf dr-priority 100"},
            "设置接口开销": {"command": "interface <interface>\nospf cost <cost>", "description": "设置OSPF接口开销", "example": "[Huawei-GigabitEthernet0/0/1] ospf cost 10"},
            "查看OSPF邻居": {"command": "display ospf peer", "description": "查看OSPF邻居关系", "example": "<Huawei> display ospf peer"},
            "查看OSPF路由": {"command": "display ospf routing", "description": "查看OSPF路由", "example": "<Huawei> display ospf routing"},
            "查看OSPF接口": {"command": "display ospf interface", "description": "查看OSPF接口信息", "example": "<Huawei> display ospf interface"},
            "重置OSPF进程": {"command": "reset ospf process", "description": "重启OSPF进程", "example": "<Huawei> reset ospf process"}
        },
        "BGP配置": {
            "启动BGP进程": {"command": "bgp <as-number>\nrouter-id <router-id>", "description": "启动BGP进程并设置Router-ID", "example": "[Huawei] bgp 65001\n[Huawei-bgp] router-id 1.1.1.1"},
            "配置BGP邻居": {"command": "peer <ip> as-number <as-number>", "description": "配置BGP对等体", "example": "[Huawei-bgp] peer 10.0.0.2 as-number 65002"},
            "配置IBGP邻居": {"command": "peer <ip> as-number <local-as>", "description": "配置IBGP对等体(同AS)", "example": "[Huawei-bgp] peer 192.168.1.2 as-number 65001"},
            "指定更新源": {"command": "peer <ip> connect-interface <interface>", "description": "指定BGP更新源接口", "example": "[Huawei-bgp] peer 10.0.0.2 connect-interface LoopBack0"},
            "宣告BGP网络": {"command": "ipv4-family unicast\nnetwork <network> mask <mask>", "description": "宣告网络到BGP", "example": "[Huawei-bgp] ipv4-family unicast\n[Huawei-bgp-af-ipv4] network 192.168.0.0 255.255.0.0"},
            "配置下一跳本地": {"command": "peer <ip> next-hop-local", "description": "设置向IBGP邻居发布路由时下一跳为本地", "example": "[Huawei-bgp-af-ipv4] peer 192.168.1.2 next-hop-local"},
            "引入直连路由": {"command": "import-route direct", "description": "引入直连路由到BGP", "example": "[Huawei-bgp-af-ipv4] import-route direct"},
            "引入静态路由": {"command": "import-route static", "description": "引入静态路由到BGP", "example": "[Huawei-bgp-af-ipv4] import-route static"},
            "设置BGP优先级": {"command": "preference external internal local", "description": "设置BGP路由优先级", "example": "[Huawei-bgp] preference 255 100 130"},
            "查看BGP邻居": {"command": "display bgp peer", "description": "查看BGP对等体状态", "example": "<Huawei> display bgp peer"},
            "查看BGP路由": {"command": "display bgp routing-table", "description": "查看BGP路由表", "example": "<Huawei> display bgp routing-table"},
            "刷新BGP连接": {"command": "refresh bgp all <import|export>", "description": "刷新BGP路由", "example": "<Huawei> refresh bgp all import"}
        },
        "RIP配置": {
            "启用RIP进程": {"command": "rip <process-id>", "description": "启动RIP进程", "example": "[Huawei] rip 1"},
            "宣告网络": {"command": "network <network>", "description": "宣告直连网络", "example": "[Huawei-rip-1] network 192.168.0.0"},
            "设置RIP版本": {"command": "version <1|2>", "description": "设置RIP版本", "example": "[Huawei-rip-1] version 2"},
            "关闭自动汇总": {"command": "undo summary", "description": "关闭RIP自动汇总", "example": "[Huawei-rip-1] undo summary"},
            "配置被动接口": {"command": "silent-interface <interface>", "description": "禁止接口发送RIP报文", "example": "[Huawei-rip-1] silent-interface Vlanif10"},
            "查看RIP路由": {"command": "display rip <process-id> route", "description": "查看RIP路由", "example": "<Huawei> display rip 1 route"},
            "查看RIP邻居": {"command": "display rip <process-id> neighbor", "description": "查看RIP邻居", "example": "<Huawei> display rip 1 neighbor"}
        }
    },
    "安全配置": {
        "ACL配置": {
            "创建基本ACL": {"command": "acl <number> [basic]", "description": "创建基本ACL(2000-2999)", "example": "[Huawei] acl 2000"},
            "创建高级ACL": {"command": "acl <number> advance", "description": "创建高级ACL(3000-3999)", "example": "[Huawei] acl 3000"},
            "创建命名ACL": {"command": "acl name <name> <basic|advance>", "description": "创建命名ACL", "example": "[Huawei] acl name SERVER_ACL advance"},
            "基本规则": {"command": "rule <id> <permit|deny> source <source> <wildcard>", "description": "配置基本ACL规则", "example": "[Huawei-acl-basic-2000] rule 5 permit source 192.168.1.0 0.0.0.255"},
            "高级规则": {"command": "rule <id> <permit|deny> <protocol> source <src> <wildcard> destination <dst> <wildcard> [<port>]", "description": "配置高级ACL规则", "example": "[Huawei-acl-adv-3000] rule 5 permit tcp source 192.168.1.0 0.0.0.255 destination 10.0.0.1 0.0.0.0 destination-port eq 80"},
            "拒绝所有": {"command": "rule <id> deny", "description": "拒绝所有流量", "example": "[Huawei-acl-adv-3000] rule 100 deny"},
            "允许所有": {"command": "rule <id> permit", "description": "允许所有流量", "example": "[Huawei-acl-adv-3000] rule 100 permit"},
            "端口匹配": {"command": "destination-port eq <port>\ndestination-port range <start> <end>", "description": "匹配目标端口", "example": "[Huawei-acl-adv-3000] rule 10 permit tcp source any destination any destination-port eq 80"},
            "时间段ACL": {"command": "time-range <name> <start> to <end>", "description": "配置时间段", "example": "[Huawei] time-range work-time 09:00 to 18:00 working-day\n[Huawei-acl-adv-3000] rule 10 permit tcp time-range work-time"},
            "接口应用ACL": {"command": "interface <interface>\ntraffic-filter <inbound|outbound> acl <number>", "description": "在接口应用ACL过滤流量", "example": "[Huawei-GigabitEthernet0/0/1] traffic-filter inbound acl 3000"},
            "查看ACL": {"command": "display acl <number>", "description": "查看ACL配置", "example": "<Huawei> display acl 3000"},
            "查看ACL匹配": {"command": "display acl <number> hit", "description": "查看ACL匹配计数", "example": "<Huawei> display acl 3000 hit"},
            "清除ACL计数": {"command": "reset acl counter <number>", "description": "清除ACL匹配计数", "example": "<Huawei> reset acl counter 3000"}
        },
        "端口安全": {
            "启用端口安全": {"command": "port-security enable", "description": "启用端口安全功能", "example": "[Huawei-GigabitEthernet0/0/1] port-security enable"},
            "最大MAC数": {"command": "port-security max-mac-num <number>", "description": "设置端口最大MAC地址数", "example": "[Huawei-GigabitEthernet0/0/1] port-security max-mac-num 1"},
            "配置安全MAC": {"command": "port-security mac-address <mac> vlan <vlan-id>", "description": "手动配置安全MAC地址", "example": "[Huawei-GigabitEthernet0/0/1] port-security mac-address 0001-0002-0003 vlan 10"},
            "自动学习MAC": {"command": "port-security mac-address sticky", "description": "启用粘性MAC自动学习", "example": "[Huawei-GigabitEthernet0/0/1] port-security mac-address sticky"},
            "安全违规处理": {"command": "port-security protect-action <protect|restrict|shutdown>", "description": "设置违规处理方式(protect丢弃/restrict告警/shutdown关闭)", "example": "[Huawei-GigabitEthernet0/0/1] port-security protect-action shutdown"},
            "老化时间": {"command": "port-security aging-time <minutes>", "description": "设置安全MAC老化时间", "example": "[Huawei-GigabitEthernet0/0/1] port-security aging-time 30"},
            "查看端口安全": {"command": "display port-security interface <interface>", "description": "查看接口端口安全状态", "example": "<Huawei> display port-security interface GigabitEthernet0/0/1"},
            "恢复违规端口": {"command": "interface <interface>\nundo shutdown", "description": "恢复被shutdown的违规端口", "example": "[Huawei-GigabitEthernet0/0/1] undo shutdown"}
        },
        "DHCP Snooping": {
            "启用DHCP Snooping": {"command": "dhcp enable\ndhcp snooping enable", "description": "全局启用DHCP Snooping", "example": "[Huawei] dhcp enable\n[Huawei] dhcp snooping enable"},
            "信任接口": {"command": "interface <interface>\ndhcp snooping trusted", "description": "配置DHCP信任接口", "example": "[Huawei-GigabitEthernet0/0/24] dhcp snooping trusted"},
            "非信任接口": {"command": "interface <interface>\ndhcp snooping check dhcp-chaddr enable\ndhcp snooping check dhcp-giaddr enable", "description": "配置非信任接口检查", "example": "[Huawei-GigabitEthernet0/0/1] dhcp snooping check dhcp-chaddr enable"},
            "VLAN启用": {"command": "vlan <vlan-id>\ndhcp snooping enable", "description": "在VLAN启用DHCP Snooping", "example": "[Huawei-vlan10] dhcp snooping enable"},
            "查看绑定表": {"command": "display dhcp snooping user-bind", "description": "查看DHCP Snooping绑定表", "example": "<Huawei> display dhcp snooping user-bind"}
        },
        "ARP安全": {
            "ARP表项限制": {"command": "interface <interface>\narp-limit maximum <number>", "description": "限制接口ARP表项数量", "example": "[Huawei-GigabitEthernet0/0/1] arp-limit maximum 50"},
            "静态ARP绑定": {"command": "arp static <ip> <mac> <interface> <vlan-id>", "description": "配置静态ARP表项", "example": "[Huawei] arp static 192.168.1.100 0001-0002-0003 GigabitEthernet0/0/1 10"},
            "ARP检测": {"command": "arp detection enable", "description": "启用ARP检测", "example": "[Huawei-vlan10] arp detection enable"},
            "ARP防御": {"command": "arp anti-attack enable", "description": "启用ARP防攻击功能", "example": "[Huawei] arp anti-attack enable"},
            "查看ARP表": {"command": "display arp", "description": "查看ARP表", "example": "<Huawei> display arp"},
            "清除ARP表": {"command": "reset arp dynamic", "description": "清除动态ARP表项", "example": "<Huawei> reset arp dynamic"}
        },
        "IPSG配置": {
            "启用IPSG": {"command": "ip source check user-bind enable", "description": "启用IP源防护", "example": "[Huawei-GigabitEthernet0/0/1] ip source check user-bind enable"},
            "静态绑定": {"command": "user-bind static ip <ip> mac <mac> interface <interface> vlan <vlan-id>", "description": "配置静态IP/MAC绑定", "example": "[Huawei] user-bind static ip 192.168.1.100 mac 0001-0002-0003 interface GigabitEthernet0/0/1 vlan 10"},
            "查看绑定表": {"command": "display dhcp snooping user-bind all", "description": "查看IPSG绑定表", "example": "<Huawei> display dhcp snooping user-bind all"}
        },
        "流量监管": {
            "配置ACL": {"command": "acl <number>\nrule <id> <permit|deny> source/destination", "description": "创建匹配流量的ACL", "example": "[Huawei] acl 3000\n[Huawei-acl-adv-3000] rule 5 permit ip source 192.168.1.0 0.0.0.255"},
            "配置流分类": {"command": "traffic classifier <name>\nif-match acl <number>", "description": "创建流分类", "example": "[Huawei] traffic_classifier CLASS_1\n[Huawei-classifier-CLASS_1] if-match acl 3000"},
            "配置流行为": {"command": "traffic behavior <name>\ncar cir <kbps> [pir <kbps>] cbs <bytes> [green <action> yellow <action> red <action>]", "description": "创建流行为配置限速", "example": "[Huawei] traffic behavior BEHAV_1\n[Huawei-behavior-BEHAV_1] car cir 10000 pir 20000 cbs 1875000 green pass yellow pass red discard"},
            "配置流策略": {"command": "traffic policy <name>\nclassifier <classifier-name> behavior <behavior-name>", "description": "创建流策略绑定分类和行为", "example": "[Huawei] traffic policy POLICY_1\n[Huawei-trafficpolicy-POLICY_1] classifier CLASS_1 behavior BEHAV_1"},
            "应用流策略": {"command": "interface <interface>\ntraffic-policy <policy-name> <inbound|outbound>", "description": "在接口应用流策略", "example": "[Huawei-GigabitEthernet0/0/1] traffic-policy POLICY_1 inbound"},
            "查看流策略": {"command": "display traffic policy <name>", "description": "查看流策略配置", "example": "<Huawei> display traffic policy POLICY_1"}
        }
    },
    "生成树配置": {
        "STP基础": {
            "启用STP": {"command": "stp enable", "description": "全局启用STP", "example": "[Huawei] stp enable"},
            "关闭STP": {"command": "stp disable", "description": "全局关闭STP", "example": "[Huawei] stp disable"},
            "配置STP模式": {"command": "stp mode <stp|rstp|mstp>", "description": "设置STP模式", "example": "[Huawei] stp mode mstp"},
            "设置桥优先级": {"command": "stp priority <priority>", "description": "设置网桥优先级(0-61440,步长4096)", "example": "[Huawei] stp priority 4096"},
            "设置根桥": {"command": "stp root <primary|secondary>", "description": "设置为主/备根桥", "example": "[Huawei] stp root primary"},
            "设置端口优先级": {"command": "interface <interface>\nstp priority <priority>", "description": "设置端口优先级", "example": "[Huawei-GigabitEthernet0/0/1] stp priority 128"},
            "设置端口开销": {"command": "interface <interface>\nstp cost <cost>", "description": "设置端口开销", "example": "[Huawei-GigabitEthernet0/0/1] stp cost 200000"},
            "启用端口边缘": {"command": "interface <interface>\nstp edged-port enable", "description": "配置边缘端口(立即转发)", "example": "[Huawei-GigabitEthernet0/0/1] stp edged-port enable"},
            "BPDU保护": {"command": "stp bpdu-protection", "description": "启用BPDU保护", "example": "[Huawei] stp bpdu-protection"},
            "根保护": {"command": "interface <interface>\nstp root-protection", "description": "配置根保护", "example": "[Huawei-GigabitEthernet0/0/24] stp root-protection"},
            "环路保护": {"command": "interface <interface>\nstp loop-protection", "description": "配置环路保护", "example": "[Huawei-GigabitEthernet0/0/1] stp loop-protection"},
            "查看STP状态": {"command": "display stp", "description": "查看STP状态", "example": "<Huawei> display stp"},
            "查看STP端口": {"command": "display stp interface <interface>", "description": "查看端口STP状态", "example": "<Huawei> display stp interface GigabitEthernet0/0/1"}
        },
        "MSTP配置": {
            "进入MST域": {"command": "stp region-configuration", "description": "进入MST域配置", "example": "[Huawei] stp region-configuration"},
            "配置域名": {"command": "region-name <name>", "description": "设置MST域名", "example": "[Huawei-mst-region] region-name MST_DOMAIN_1"},
            "配置实例映射": {"command": "instance <instance-id> vlan <vlan-id-list>", "description": "配置VLAN到实例映射", "example": "[Huawei-mst-region] instance 1 vlan 10 20\n[Huawei-mst-region] instance 2 vlan 30 40"},
            "配置修订级别": {"command": "revision-level <level>", "description": "设置MST修订级别", "example": "[Huawei-mst-region] revision-level 1"},
            "激活MST域": {"command": "active region-configuration", "description": "激活MST域配置", "example": "[Huawei-mst-region] active region-configuration"},
            "设置实例优先级": {"command": "stp instance <instance-id> priority <priority>", "description": "设置实例网桥优先级", "example": "[Huawei] stp instance 1 priority 4096"},
            "设置实例根桥": {"command": "stp instance <instance-id> root <primary|secondary>", "description": "设置实例根桥", "example": "[Huawei] stp instance 1 root primary"},
            "查看MST配置": {"command": "display stp region-configuration", "description": "查看MST域配置", "example": "<Huawei> display stp region-configuration"}
        }
    },
    "高可用配置": {
        "VRRP配置": {
            "配置VRRP组": {"command": "interface vlanif <vlan-id>\nvrrp vrid <vrid> virtual-ip <vip>", "description": "配置VRRP虚拟网关", "example": "[Huawei-Vlanif10] vrrp vrid 1 virtual-ip 192.168.10.254"},
            "设置优先级": {"command": "vrrp vrid <vrid> priority <priority>", "description": "设置VRRP优先级", "example": "[Huawei-Vlanif10] vrrp vrid 1 priority 120"},
            "配置抢占": {"command": "vrrp vrid <vrid> preempt-mode <timer|delay>", "description": "配置抢占模式", "example": "[Huawei-Vlanif10] vrrp vrid 1 preempt-mode timer delay 20"},
            "跟踪接口": {"command": "vrrp vrid <vrid> track interface <interface> reduced <value>", "description": "跟踪接口状态降低优先级", "example": "[Huawei-Vlanif10] vrrp vrid 1 track interface GigabitEthernet0/0/1 reduced 30"},
            "认证配置": {"command": "vrrp vrid <vrid> authentication-mode <simple|md5> <password>", "description": "配置VRRP认证", "example": "[Huawei-Vlanif10] vrrp vrid 1 authentication-mode md5 Huawei@123"},
            "查看VRRP状态": {"command": "display vrrp", "description": "查看VRRP状态", "example": "<Huawei> display vrrp"},
            "查看VRRP详细": {"command": "display vrrp detail", "description": "查看VRRP详细信息", "example": "<Huawei> display vrrp detail"}
        },
        "堆叠配置": {
            "启用堆叠": {"command": "stack enable", "description": "启用堆叠功能", "example": "[Huawei] stack enable"},
            "配置堆叠域": {"command": "stack domain <domain-id>", "description": "配置堆叠域ID", "example": "[Huawei] stack domain 10"},
            "配置堆叠ID": {"command": "stack slot <slot-id> priority <priority>", "description": "设置堆叠优先级", "example": "[Huawei] stack slot 0 priority 150"},
            "配置堆叠端口": {"command": "interface stack-port <port-id>\nport member-group interface <interface>", "description": "配置堆叠物理端口", "example": "[Huawei] interface stack-port 0/1\n[Huawei-Stack-Port0/1] port member-group interface GigabitEthernet0/0/1"},
            "查看堆叠状态": {"command": "display stack", "description": "查看堆叠状态", "example": "<Huawei> display stack"},
            "查看堆叠拓扑": {"command": "display stack topology", "description": "查看堆叠拓扑", "example": "<Huawei> display stack topology"}
        },
        "BFD配置": {
            "启用BFD": {"command": "bfd", "description": "全局启用BFD", "example": "[Huawei] bfd"},
            "创建BFD会话": {"command": "bfd <session-name> bind <peer-ip> <source-ip>", "description": "创建BFD会话", "example": "[Huawei] bfd session1 bind peer-ip 10.0.0.2 source-ip 10.0.0.1"},
            "配置检测参数": {"command": "discriminator local <value>\ndiscriminator remote <value>\nmin-tx-interval <ms>\nmin-rx-interval <ms>", "description": "配置BFD参数", "example": "[Huawei-bfd-session-session1] discriminator local 1\n[Huawei-bfd-session-session1] discriminator remote 2\n[Huawei-bfd-session-session1] min-tx-interval 100\n[Huawei-bfd-session-session1] min-rx-interval 100"},
            "提交BFD会话": {"command": "commit", "description": "提交BFD会话配置", "example": "[Huawei-bfd-session-session1] commit"},
            "查看BFD会话": {"command": "display bfd session", "description": "查看BFD会话", "example": "<Huawei> display bfd session"}
        }
    },
    "管理与监控": {
        "日志配置": {
            "启用信息中心": {"command": "info-center enable", "description": "启用信息中心", "example": "[Huawei] info-center enable"},
            "配置日志主机": {"command": "info-center loghost <ip> [facility <facility>]", "description": "配置日志服务器", "example": "[Huawei] info-center loghost 192.168.1.100 facility local7"},
            "配置日志级别": {"command": "info-center source <module> level <level>", "description": "配置日志级别(emergencies/alerts/critical/errors/warnings/notifications/informational/debugging)", "example": "[Huawei] info-center source default level informational"},
            "配置日志缓冲": {"command": "info-center logbuffer size <size>", "description": "配置日志缓冲区大小", "example": "[Huawei] info-center logbuffer size 1024"},
            "启用终端显示": {"command": "terminal monitor\nterminal logging", "description": "终端显示日志", "example": "<Huawei> terminal monitor\n<Huawei> terminal logging"},
            "查看日志": {"command": "display logbuffer", "description": "查看日志缓冲区", "example": "<Huawei> display logbuffer"},
            "清除日志": {"command": "reset logbuffer", "description": "清除日志缓冲区", "example": "<Huawei> reset logbuffer"}
        },
        "SNMP配置": {
            "启用SNMP": {"command": "snmp-agent", "description": "启用SNMP Agent", "example": "[Huawei] snmp-agent"},
            "设置SNMP版本": {"command": "snmp-agent sys-info version <v1|v2c|v3|all>", "description": "设置SNMP版本", "example": "[Huawei] snmp-agent sys-info version v2c v3"},
            "配置只读共同体": {"command": "snmp-agent community read <community>", "description": "配置SNMP只读共同体", "example": "[Huawei] snmp-agent community read public"},
            "配置读写共同体": {"command": "snmp-agent community write <community>", "description": "配置SNMP读写共同体", "example": "[Huawei] snmp-agent community write private"},
            "配置Trap": {"command": "snmp-agent trap enable", "description": "启用Trap", "example": "[Huawei] snmp-agent trap enable"},
            "配置Trap目标": {"command": "snmp-agent target-host trap-paramsname <params> address <ip> params securityname <community>", "description": "配置Trap目标主机", "example": "[Huawei] snmp-agent target-host trap-paramsname NMS1 address 192.168.1.100 params securityname public"},
            "配置系统信息": {"command": "snmp-agent sys-info contact <contact>\nsnmp-agent sys-info location <location>", "description": "配置系统联系人/位置", "example": "[Huawei] snmp-agent sys-info contact admin@company.com\n[Huawei] snmp-agent sys-info location 'IDC_Room_A'"},
            "查看SNMP配置": {"command": "display snmp-agent sys-info", "description": "查看SNMP系统信息", "example": "<Huawei> display snmp-agent sys-info"}
        },
        "NTP配置": {
            "启用NTP": {"command": "ntp-service enable", "description": "启用NTP服务", "example": "[Huawei] ntp-service enable"},
            "配置NTP服务器": {"command": "ntp-service unicast-server <ip> [version <v>] [preferred]", "description": "配置NTP服务器", "example": "[Huawei] ntp-service unicast-server 192.168.1.100 version 4 preferred"},
            "配置时区": {"command": "clock timezone <name> <add|minus> <hours> [<minutes>]", "description": "配置时区", "example": "[Huawei] clock timezone BJ add 08:00"},
            "查看NTP状态": {"command": "display ntp-service status", "description": "查看NTP状态", "example": "<Huawei> display ntp-service status"},
            "查看NTP会话": {"command": "display ntp-service sessions", "description": "查看NTP会话", "example": "<Huawei> display ntp-service sessions"}
        },
        "NetStream配置": {
            "启用NetStream": {"command": "ip netstream timeout active <minutes>\nip netstream timeout inactive <seconds>", "description": "配置NetStream超时", "example": "[Huawei] ip netstream timeout active 10"},
            "接口启用": {"command": "interface <interface>\nip netstream <inbound|outbound>", "description": "接口启用NetStream", "example": "[Huawei-GigabitEthernet0/0/1] ip netstream inbound"},
            "配置输出目标": {"command": "ip netstream export host <ip> <port>", "description": "配置NetStream输出目标", "example": "[Huawei] ip netstream export host 192.168.1.100 9996"},
            "查看统计": {"command": "display ip netstream cache", "description": "查看NetStream缓存", "example": "<Huawei> display ip netstream cache"}
        }
    },
    "QoS配置": {
        "优先级映射": {
            "配置信任DSCP": {"command": "interface <interface>\ntrust dscp", "description": "信任DSCP优先级", "example": "[Huawei-GigabitEthernet0/0/1] trust dscp"},
            "配置信任802.1p": {"command": "interface <interface>\ntrust 8021p", "description": "信任802.1p优先级", "example": "[Huawei-GigabitEthernet0/0/1] trust 8021p"},
            "配置端口优先级": {"command": "interface <interface>\nport priority <priority>", "description": "设置端口优先级", "example": "[Huawei-GigabitEthernet0/0/1] port priority 5"},
            "映射DSCP": {"command": "qos dscp <dscp> <phb> <color>", "description": "配置DSCP到PHB映射", "example": "[Huawei] qos dscp 46 ef green"}
        },
        "流量整形": {
            "接口限速": {"command": "interface <interface>\nqos lr <inbound|outbound> cir <kbps> cbs <bytes>", "description": "接口限速(线路速率)", "example": "[Huawei-GigabitEthernet0/0/1] qos lr outbound cir 10000 cbs 1875000"},
            "队列整形": {"command": "interface <interface>\nqos queue <queue-id> shaping cir <kbps>", "description": "队列流量整形", "example": "[Huawei-GigabitEthernet0/0/1] qos queue 0 shaping cir 5000"}
        },
        "拥塞管理": {
            "配置调度模式": {"command": "interface <interface>\nqos queue <queue-id> wfq", "description": "配置WFQ调度", "example": "[Huawei-GigabitEthernet0/0/1] qos queue 0 wfq"},
            "配置优先队列": {"command": "interface <interface>\nqos pq <queue-id>", "description": "配置优先队列", "example": "[Huawei-GigabitEthernet0/0/1] qos pq 5 6 7"},
            "配置WRR": {"command": "interface <interface>\nqos wrr queue <queue-id> weight <weight>", "description": "配置WRR调度权重", "example": "[Huawei-GigabitEthernet0/0/1] qos wrr queue 0 weight 10\n[Huawei-GigabitEthernet0/0/1] qos wrr queue 1 weight 20"}
        }
    },
    "IPv6配置": {
        "基础配置": {
            "启用IPv6": {"command": "ipv6", "description": "全局启用IPv6", "example": "[Huawei] ipv6"},
            "接口IPv6地址": {"command": "interface <interface>\nipv6 enable\nipv6 address <ipv6>/<prefix>", "description": "配置接口IPv6地址", "example": "[Huawei-GigabitEthernet0/0/1] ipv6 enable\n[Huawei-GigabitEthernet0/0/1] ipv6 address 2001:db8::1/64"},
            "自动配置地址": {"command": "ipv6 address auto link-local", "description": "自动配置链路本地地址", "example": "[Huawei-GigabitEthernet0/0/1] ipv6 address auto link-local"},
            "查看IPv6接口": {"command": "display ipv6 interface <interface>", "description": "查看接口IPv6信息", "example": "<Huawei> display ipv6 interface GigabitEthernet0/0/1"},
            "查看IPv6路由": {"command": "display ipv6 routing-table", "description": "查看IPv6路由表", "example": "<Huawei> display ipv6 routing-table"},
            "Ping IPv6": {"command": "ping ipv6 <ipv6>", "description": "测试IPv6连通性", "example": "<Huawei> ping ipv6 2001:db8::1"}
        },
        "IPv6路由": {
            "静态路由": {"command": "ipv6 route-static <dest>/<prefix> <next-hop>", "description": "配置IPv6静态路由", "example": "[Huawei] ipv6 route-static ::/0 2001:db8::ffff"},
            "OSPFv3": {"command": "ospfv3 <process-id>\nrouter-id <router-id>\narea <area-id>", "description": "配置OSPFv3", "example": "[Huawei] ospfv3 1\n[Huawei-ospfv3-1] router-id 1.1.1.1\n[Huawei-ospfv3-1] area 0"}
        }
    }
}

HUAWEI_CASES = [
    {
        "title": "接入交换机基础配置",
        "description": "接入层交换机初始化配置，包括VLAN、管理IP、SSH、端口安全",
        "steps": [
            "# 1. 系统基本配置",
            "sysname Access-SW-01",
            "",
            "# 2. 创建VLAN",
            "vlan batch 10 20 30 100",
            "vlan 10",
            " name Sales_Department",
            "vlan 20",
            " name Engineering",
            "vlan 30",
            " name Finance",
            "vlan 100",
            " name Management",
            "",
            "# 3. 配置VLANIF网关(如果设备支持三层)",
            "interface Vlanif 100",
            " ip address 192.168.100.1 255.255.255.0",
            "",
            "# 4. 配置管理IP",
            "interface Vlanif 1",
            " ip address 192.168.1.10 255.255.255.0",
            "",
            "# 5. 配置默认网关",
            "ip route-static 0.0.0.0 0.0.0.0 192.168.1.254",
            "",
            "# 6. 配置Access端口",
            "interface range GigabitEthernet 0/0/1 to GigabitEthernet 0/0/10",
            " port link-type access",
            " port default vlan 10",
            " description Sales_Users",
            "",
            "interface range GigabitEthernet 0/0/11 to GigabitEthernet 0/0/20",
            " port link-type access",
            " port default vlan 20",
            " description Engineering_Users",
            "",
            "# 7. 配置Trunk上行口",
            "interface GigabitEthernet 0/0/24",
            " port link-type trunk",
            " port trunk allow-pass vlan 10 20 30 100",
            " description Uplink_to_Core",
            "",
            "# 8. 配置SSH",
            "rsa local-key-pair create",
            "stelnet server enable",
            "ssh user admin",
            "ssh user admin authentication-type password",
            "ssh user admin service-type stelnet",
            "local-user admin",
            " password cipher Admin@123",
            " service-type ssh",
            " level 15",
            "",
            "user-interface vty 0 4",
            " authentication-mode aaa",
            " protocol inbound ssh",
            "",
            "# 9. 配置端口安全",
            "interface range GigabitEthernet 0/0/1 to GigabitEthernet 0/0/20",
            " port-security enable",
            " port-security max-mac-num 2",
            " port-security protect-action shutdown",
            "",
            "# 10. 配置STP边缘端口",
            "interface range GigabitEthernet 0/0/1 to GigabitEthernet 0/0/20",
            " stp edged-port enable",
            "",
            "# 11. 保存配置",
            "save"
        ]
    },
    {
        "title": "核心交换机配置",
        "description": "核心交换机完整配置，包括VLANIF、路由、ACL、VRRP",
        "steps": [
            "# 1. 系统配置",
            "sysname Core-SW-01",
            "",
            "# 2. 创建VLAN",
            "vlan batch 10 20 30 100 200",
            "",
            "# 3. 配置VLANIF网关",
            "interface Vlanif 10",
            " ip address 192.168.10.1 255.255.255.0",
            " description Gateway_VLAN10_Sales",
            "",
            "interface Vlanif 20",
            " ip address 192.168.20.1 255.255.255.0",
            " description Gateway_VLAN20_Engineering",
            "",
            "interface Vlanif 30",
            " ip address 192.168.30.1 255.255.255.0",
            " description Gateway_VLAN30_Finance",
            "",
            "interface Vlanif 100",
            " ip address 192.168.100.1 255.255.255.0",
            " description Management_Network",
            "",
            "interface Vlanif 200",
            " ip address 10.0.0.1 255.255.255.252",
            " description WAN_Uplink",
            "",
            "# 4. 配置DHCP",
            "dhcp enable",
            "ip pool vlan10_pool",
            " network 192.168.10.0 mask 255.255.255.0",
            " gateway-list 192.168.10.1",
            " dns-list 8.8.8.8 114.114.114.114",
            " lease day 3",
            "",
            "interface Vlanif 10",
            " dhcp select global",
            "",
            "# 5. 配置静态路由",
            "ip route-static 0.0.0.0 0.0.0.0 10.0.0.2",
            "",
            "# 6. 配置OSPF",
            "ospf 1 router-id 1.1.1.1",
            " area 0",
            "  network 192.168.0.0 0.0.255.255",
            "  network 10.0.0.0 0.0.0.3",
            "",
            "# 7. 配置ACL",
            "acl 3000",
            " rule 5 deny ip source 192.168.20.0 0.0.0.255 destination 192.168.30.0 0.0.0.255",
            " rule 10 permit ip",
            "",
            "interface Vlanif 20",
            " traffic-filter outbound acl 3000",
            "",
            "# 8. 配置VRRP",
            "interface Vlanif 10",
            " vrrp vrid 1 virtual-ip 192.168.10.254",
            " vrrp vrid 1 priority 120",
            " vrrp vrid 1 preempt-mode timer delay 20",
            "",
            "# 9. 配置NTP",
            "ntp-service enable",
            "ntp-service unicast-server 192.168.100.100",
            "clock timezone BJ add 08:00",
            "",
            "# 10. 配置日志",
            "info-center enable",
            "info-center loghost 192.168.100.101",
            "",
            "# 11. 配置SNMP",
            "snmp-agent",
            "snmp-agent sys-info version v2c",
            "snmp-agent community read Public@123",
            "snmp-agent sys-info contact admin@company.com",
            "snmp-agent sys-info location 'IDC_Room_A'",
            "",
            "save"
        ]
    },
    {
        "title": "链路聚合配置",
        "description": "Eth-Trunk链路聚合配置，LACP模式",
        "steps": [
            "# 1. 创建Eth-Trunk接口",
            "interface Eth-Trunk 1",
            " description To_Core_Switch",
            " port link-type trunk",
            " port trunk allow-pass vlan 10 20 30",
            " mode lacp-static",
            " max active-linknumber 2",
            " load-balance src-dst-ip",
            "",
            "# 2. 添加成员接口",
            "interface GigabitEthernet 0/0/1",
            " eth-trunk 1",
            "",
            "interface GigabitEthernet 0/0/2",
            " eth-trunk 1",
            "",
            "interface GigabitEthernet 0/0/3",
            " eth-trunk 1",
            "",
            "# 3. 配置LACP优先级(可选)",
            "lacp priority 100",
            "",
            "# 4. 验证配置",
            "display eth-trunk 1",
            "display lacp statistics eth-trunk 1"
        ]
    },
    {
        "title": "MSTP多生成树配置",
        "description": "MSTP多实例生成树配置，实现负载均衡",
        "steps": [
            "# 1. 配置MSTP域",
            "stp region-configuration",
            " region-name COMPANY_MST",
            " revision-level 1",
            " instance 1 vlan 10 20",
            " instance 2 vlan 30 40",
            " active region-configuration",
            "",
            "# 2. 配置STP模式",
            "stp mode mstp",
            "",
            "# 3. 核心交换机1配置",
            "stp instance 1 root primary",
            "stp instance 2 root secondary",
            "",
            "# 4. 核心交换机2配置",
            "stp instance 1 root secondary",
            "stp instance 2 root primary",
            "",
            "# 5. 启用BPDU保护",
            "stp bpdu-protection",
            "",
            "# 6. 配置边缘端口",
            "interface range GigabitEthernet 0/0/1 to GigabitEthernet 0/0/20",
            " stp edged-port enable",
            "",
            "# 7. 验证配置",
            "display stp region-configuration",
            "display stp instance 1",
            "display stp instance 2"
        ]
    },
    {
        "title": "DHCP服务器配置",
        "description": "交换机作为DHCP服务器配置",
        "steps": [
            "# 1. 启用DHCP服务",
            "dhcp enable",
            "",
            "# 2. 配置地址池",
            "ip pool vlan10_pool",
            " network 192.168.10.0 mask 255.255.255.0",
            " gateway-list 192.168.10.1",
            " dns-list 8.8.8.8 114.114.114.114",
            " excluded-ip-address 192.168.10.1 192.168.10.10",
            " lease day 3",
            "",
            "ip pool vlan20_pool",
            " network 192.168.20.0 mask 255.255.255.0",
            " gateway-list 192.168.20.1",
            " dns-list 8.8.8.8",
            " lease day 7",
            "",
            "# 3. 在VLANIF接口启用DHCP",
            "interface Vlanif 10",
            " dhcp select global",
            "",
            "interface Vlanif 20",
            " dhcp select global",
            "",
            "# 4. 配置DHCP中继(如需要)",
            "interface Vlanif 30",
            " dhcp select relay",
            " dhcp relay server-ip 192.168.100.100",
            "",
            "# 5. 查看DHCP配置",
            "display ip pool",
            "display dhcp server statistics"
        ]
    },
    {
        "title": "QoS流量限速配置",
        "description": "基于ACL的流量限速配置",
        "steps": [
            "# 1. 创建ACL匹配流量",
            "acl 3000",
            " rule 5 permit ip source 192.168.10.0 0.0.0.255",
            "",
            "# 2. 创建流分类",
            "traffic classifier CLASS_LIMIT",
            " if-match acl 3000",
            "",
            "# 3. 创建流行为",
            "traffic behavior BEHAV_LIMIT",
            " car cir 10000 pir 20000 cbs 1875000 green pass yellow pass red discard",
            "",
            "# 4. 创建流策略",
            "traffic policy POLICY_LIMIT",
            " classifier CLASS_LIMIT behavior BEHAV_LIMIT",
            "",
            "# 5. 应用流策略",
            "interface GigabitEthernet 0/0/1",
            " traffic-policy POLICY_LIMIT inbound",
            "",
            "# 6. 验证配置",
            "display traffic policy POLICY_LIMIT"
        ]
    },
    {
        "title": "端口镜像配置",
        "description": "配置端口镜像用于流量监控",
        "steps": [
            "# 1. 配置观察端口",
            "observe-port 1 interface GigabitEthernet 0/0/24",
            "",
            "# 2. 配置镜像端口(镜像所有流量)",
            "interface GigabitEthernet 0/0/1",
            " port-mirroring to observe-port 1 both",
            "",
            "# 3. 配置镜像端口(只镜像入方向)",
            "interface GigabitEthernet 0/0/2",
            " port-mirroring to observe-port 1 inbound",
            "",
            "# 4. 配置流镜像(基于ACL)",
            "acl 3000",
            " rule 5 permit tcp destination-port eq 80",
            "",
            "traffic classifier CLASS_WEB",
            " if-match acl 3000",
            "",
            "traffic behavior BEHAV_MIRROR",
            " mirroring to observe-port 1",
            "",
            "traffic policy POLICY_MIRROR",
            " classifier CLASS_WEB behavior BEHAV_MIRROR",
            "",
            "interface GigabitEthernet 0/0/3",
            " traffic-policy POLICY_MIRROR inbound",
            "",
            "# 5. 验证配置",
            "display observe-port",
            "display port-mirroring"
        ]
    },
    {
        "title": "堆叠配置",
        "description": "华为交换机堆叠配置",
        "steps": [
            "# 交换机1配置",
            "# 1. 配置堆叠域",
            "stack domain 10",
            "",
            "# 2. 配置堆叠优先级",
            "stack slot 0 priority 150",
            "",
            "# 3. 配置堆叠端口",
            "interface stack-port 0/1",
            " port member-group interface GigabitEthernet 0/0/47",
            " port member-group interface GigabitEthernet 0/0/48",
            "",
            "# 4. 启用堆叠",
            "stack enable",
            "",
            "# 交换机2配置",
            "stack domain 10",
            "stack slot 0 priority 100",
            "",
            "# 5. 验证配置",
            "display stack",
            "display stack configuration",
            "display stack topology"
        ]
    }
]
